export interface EndangeredLanguage {
  name: string;
  region: string;
  country: string;
  speakers: string;
  status: "vulnerable" | "endangered" | "critically_endangered" | "dormant";
  family: string;
  uniqueFeature: string;
  coordinates: { lat: number; lng: number };
}

export const endangeredLanguages: EndangeredLanguage[] = [
  {
    name: "Ainu",
    region: "Hokkaido",
    country: "Japan",
    speakers: "< 10 native",
    status: "critically_endangered",
    family: "Isolate",
    uniqueFeature: "Polysynthetic structure — a single verb can contain an entire sentence's worth of meaning.",
    coordinates: { lat: 43.06, lng: 141.35 },
  },
  {
    name: "Livonian",
    region: "Livonian Coast",
    country: "Latvia",
    speakers: "< 20",
    status: "critically_endangered",
    family: "Uralic (Finnic)",
    uniqueFeature: "The southernmost Finnic language, with heavy Baltic influence creating a unique hybrid grammar.",
    coordinates: { lat: 57.56, lng: 21.99 },
  },
  {
    name: "Saterland Frisian",
    region: "Lower Saxony",
    country: "Germany",
    speakers: "~2,000",
    status: "endangered",
    family: "Germanic (Frisian)",
    uniqueFeature: "Last surviving dialect of East Frisian, preserved by geographic isolation in a bog region.",
    coordinates: { lat: 53.08, lng: 7.69 },
  },
  {
    name: "Archi",
    region: "Dagestan",
    country: "Russia",
    speakers: "~970",
    status: "endangered",
    family: "Northeast Caucasian",
    uniqueFeature: "The verb system can produce over 1.5 million distinct forms per verb — the most complex morphology of any known language.",
    coordinates: { lat: 42.17, lng: 46.42 },
  },
  {
    name: "Silbo Gomero",
    region: "La Gomera, Canary Islands",
    country: "Spain",
    speakers: "~22,000 (taught in schools)",
    status: "vulnerable",
    family: "Whistled register of Spanish",
    uniqueFeature: "A fully functional whistled language that can carry across valleys up to 5 km — one of the few whistled languages still in active use.",
    coordinates: { lat: 28.09, lng: -17.11 },
  },
  {
    name: "Taa (!Xóõ)",
    region: "Kalahari",
    country: "Botswana",
    speakers: "~2,500",
    status: "endangered",
    family: "Tuu (Khoisan)",
    uniqueFeature: "Has up to 164 consonants including over 80 clicks — possibly the largest sound inventory of any language on Earth.",
    coordinates: { lat: -23.65, lng: 21.82 },
  },
  {
    name: "Nǀuu",
    region: "Northern Cape",
    country: "South Africa",
    speakers: "< 10",
    status: "critically_endangered",
    family: "Tuu (Khoisan)",
    uniqueFeature: "One of the last surviving Southern Khoisan languages, with a click consonant system rivaling Taa in complexity.",
    coordinates: { lat: -28.57, lng: 20.89 },
  },
  {
    name: "Hadza",
    region: "Lake Eyasi region",
    country: "Tanzania",
    speakers: "~1,000",
    status: "endangered",
    family: "Isolate",
    uniqueFeature: "Spoken by one of the last hunter-gatherer communities in Africa; uses click consonants despite no proven genetic relationship to Khoisan.",
    coordinates: { lat: -3.75, lng: 35.02 },
  },
  {
    name: "Pirahã",
    region: "Amazon",
    country: "Brazil",
    speakers: "~800",
    status: "endangered",
    family: "Mura",
    uniqueFeature: "Controversially claimed to lack recursion, color terms, and number words — challenges Chomsky's universal grammar theory.",
    coordinates: { lat: -7.25, lng: -62.78 },
  },
  {
    name: "Ayapaneco",
    region: "Tabasco",
    country: "Mexico",
    speakers: "< 5",
    status: "critically_endangered",
    family: "Mixe-Zoque",
    uniqueFeature: "Once down to two known speakers who reportedly refused to speak to each other; revitalization efforts have since begun.",
    coordinates: { lat: 17.99, lng: -93.38 },
  },
  {
    name: "Kaixana",
    region: "Amazonas",
    country: "Brazil",
    speakers: "1",
    status: "critically_endangered",
    family: "Unclassified (possibly Arawakan)",
    uniqueFeature: "One of the world's most endangered languages with a single known speaker — an entire worldview held by one person.",
    coordinates: { lat: -3.39, lng: -64.72 },
  },
  {
    name: "Taushiro",
    region: "Loreto",
    country: "Peru",
    speakers: "1",
    status: "critically_endangered",
    family: "Isolate",
    uniqueFeature: "A language isolate with no known relatives, spoken by a single elder in the Peruvian Amazon.",
    coordinates: { lat: -4.55, lng: -76.05 },
  },
  {
    name: "Chamicuro",
    region: "Loreto",
    country: "Peru",
    speakers: "< 10",
    status: "critically_endangered",
    family: "Arawakan",
    uniqueFeature: "Younger generation has shifted entirely to Spanish; the language survives only in the memories of elders.",
    coordinates: { lat: -5.15, lng: -75.62 },
  },
  {
    name: "Ter Sami",
    region: "Kola Peninsula",
    country: "Russia",
    speakers: "~2",
    status: "critically_endangered",
    family: "Uralic (Sami)",
    uniqueFeature: "The easternmost Sami language, heavily influenced by Russian; nearly all speakers are elderly.",
    coordinates: { lat: 68.05, lng: 35.08 },
  },
  {
    name: "Pite Sami",
    region: "Norrbotten / Nordland",
    country: "Sweden / Norway",
    speakers: "~30",
    status: "critically_endangered",
    family: "Uralic (Sami)",
    uniqueFeature: "Has a distinctive three-way vowel length contrast (short, half-long, long) unusual even among Sami languages.",
    coordinates: { lat: 66.34, lng: 17.34 },
  },
  {
    name: "Ume Sami",
    region: "Västerbotten / Nordland",
    country: "Sweden / Norway",
    speakers: "~10",
    status: "critically_endangered",
    family: "Uralic (Sami)",
    uniqueFeature: "Transitional between North and South Sami, making it linguistically significant for understanding Sami language divergence.",
    coordinates: { lat: 65.32, lng: 16.47 },
  },
  {
    name: "Manx",
    region: "Isle of Man",
    country: "United Kingdom",
    speakers: "~1,800 (revived)",
    status: "vulnerable",
    family: "Celtic (Goidelic)",
    uniqueFeature: "Was declared extinct in 1974 when the last native speaker died, but has been successfully revived — children now learn it as a first language.",
    coordinates: { lat: 54.24, lng: -4.55 },
  },
  {
    name: "Cornish",
    region: "Cornwall",
    country: "United Kingdom",
    speakers: "~600 fluent",
    status: "vulnerable",
    family: "Celtic (Brythonic)",
    uniqueFeature: "Extinct by 1777, now revived with several hundred fluent speakers. One of the most successful language revival stories.",
    coordinates: { lat: 50.27, lng: -5.05 },
  },
  {
    name: "Scottish Gaelic",
    region: "Highlands and Islands",
    country: "United Kingdom",
    speakers: "~57,000",
    status: "endangered",
    family: "Celtic (Goidelic)",
    uniqueFeature: "Features initial consonant mutations (lenition) that change the first sound of words based on grammar — b becomes bh [v].",
    coordinates: { lat: 57.47, lng: -7.36 },
  },
  {
    name: "Irish (Gaeilge)",
    region: "Gaeltacht regions",
    country: "Ireland",
    speakers: "~70,000 daily",
    status: "endangered",
    family: "Celtic (Goidelic)",
    uniqueFeature: "Official first language of Ireland, yet only ~2% use it daily. Extensive government support but declining native-speaker communities.",
    coordinates: { lat: 53.27, lng: -9.51 },
  },
  {
    name: "Breton",
    region: "Brittany",
    country: "France",
    speakers: "~210,000",
    status: "endangered",
    family: "Celtic (Brythonic)",
    uniqueFeature: "The only Celtic language spoken on the European continent; closely related to Cornish and Welsh.",
    coordinates: { lat: 48.39, lng: -4.49 },
  },
  {
    name: "Occitan",
    region: "Southern France, Monaco, parts of Spain/Italy",
    country: "France",
    speakers: "~100,000 fluent",
    status: "endangered",
    family: "Romance",
    uniqueFeature: "Language of the medieval troubadours who invented the concept of courtly love — profoundly influenced European literature.",
    coordinates: { lat: 43.60, lng: 1.44 },
  },
  {
    name: "Aromanian",
    region: "Balkans",
    country: "Greece / Albania / North Macedonia / Romania",
    speakers: "~250,000",
    status: "endangered",
    family: "Romance",
    uniqueFeature: "Descended from Latin spoken in the Balkans, evolved separately from Romanian for over 1,000 years; has no official status in any country.",
    coordinates: { lat: 40.63, lng: 20.78 },
  },
  {
    name: "Ladino (Judeo-Spanish)",
    region: "Diaspora (Israel, Turkey, Greece)",
    country: "Israel / Turkey",
    speakers: "~60,000",
    status: "endangered",
    family: "Romance",
    uniqueFeature: "Preserves 15th-century Castilian Spanish grammar and vocabulary — a linguistic time capsule of pre-expulsion Spain.",
    coordinates: { lat: 41.01, lng: 28.98 },
  },
  {
    name: "Yiddish",
    region: "Diaspora, Israel, USA",
    country: "Global",
    speakers: "~600,000",
    status: "vulnerable",
    family: "Germanic",
    uniqueFeature: "A High German language written in Hebrew script, with Slavic and Hebrew components — the lingua franca of Ashkenazi Jewish life for a millennium.",
    coordinates: { lat: 40.71, lng: -73.97 },
  },
  {
    name: "Okinawan",
    region: "Okinawa",
    country: "Japan",
    speakers: "~400,000 (mostly elderly)",
    status: "endangered",
    family: "Japonic (Ryukyuan)",
    uniqueFeature: "Has glottal stops and vowel distinctions absent in Standard Japanese; speakers above 60 are the primary carriers.",
    coordinates: { lat: 26.34, lng: 127.80 },
  },
  {
    name: "Jeju",
    region: "Jeju Island",
    country: "South Korea",
    speakers: "~5,000 (elderly)",
    status: "critically_endangered",
    family: "Koreanic",
    uniqueFeature: "So different from Standard Korean that linguists debate whether it is a separate language; UNESCO classifies it as critically endangered.",
    coordinates: { lat: 33.49, lng: 126.53 },
  },
  {
    name: "Nivkh",
    region: "Sakhalin, Amur River",
    country: "Russia",
    speakers: "~200",
    status: "critically_endangered",
    family: "Isolate",
    uniqueFeature: "A language isolate with a counting system that uses different number words depending on what is being counted (flat objects, long objects, animals, etc.).",
    coordinates: { lat: 52.95, lng: 141.71 },
  },
  {
    name: "Itelmen",
    region: "Kamchatka",
    country: "Russia",
    speakers: "~80",
    status: "critically_endangered",
    family: "Chukotko-Kamchatkan",
    uniqueFeature: "Has a base-20 counting system and complex polysynthetic verbs that can incorporate multiple nouns.",
    coordinates: { lat: 55.95, lng: 157.51 },
  },
  {
    name: "Chulym",
    region: "Tomsk Oblast",
    country: "Russia",
    speakers: "~15",
    status: "critically_endangered",
    family: "Turkic",
    uniqueFeature: "An isolated Turkic language that developed in complete separation from other Turkic peoples for centuries.",
    coordinates: { lat: 56.58, lng: 87.47 },
  },
  {
    name: "Koro",
    region: "Arunachal Pradesh",
    country: "India",
    speakers: "~1,000",
    status: "endangered",
    family: "Sino-Tibetan",
    uniqueFeature: "Discovered by linguists only in 2010 during a National Geographic expedition — had been mistakenly classified as a dialect of Aka.",
    coordinates: { lat: 27.17, lng: 92.38 },
  },
  {
    name: "Ongota",
    region: "South Omo Zone",
    country: "Ethiopia",
    speakers: "~12",
    status: "critically_endangered",
    family: "Isolate / Afroasiatic (debated)",
    uniqueFeature: "One of the most endangered languages in Africa; its classification is so uncertain it may be the last remnant of a lost language family.",
    coordinates: { lat: 5.28, lng: 36.55 },
  },
  {
    name: "Chaná",
    region: "Entre Ríos",
    country: "Argentina",
    speakers: "1",
    status: "critically_endangered",
    family: "Charruan",
    uniqueFeature: "Thought to be extinct for 200 years until a single speaker was found in 2005, triggering documentation efforts.",
    coordinates: { lat: -32.48, lng: -60.30 },
  },
  {
    name: "Tinigua",
    region: "Meta Department",
    country: "Colombia",
    speakers: "1",
    status: "critically_endangered",
    family: "Isolate",
    uniqueFeature: "A language isolate spoken by a single elder; represents a unique thread of human linguistic history about to be severed.",
    coordinates: { lat: 2.75, lng: -73.96 },
  },
  {
    name: "Resígaro",
    region: "Loreto",
    country: "Peru",
    speakers: "< 5",
    status: "critically_endangered",
    family: "Arawakan",
    uniqueFeature: "Heavy influence from Bora language due to centuries of intermarriage, creating a unique Arawakan-Boran hybrid.",
    coordinates: { lat: -2.88, lng: -72.22 },
  },
  {
    name: "Tanema",
    region: "Vanikoro, Temotu Province",
    country: "Solomon Islands",
    speakers: "1",
    status: "critically_endangered",
    family: "Austronesian (Oceanic)",
    uniqueFeature: "A single remaining speaker on an island also home to Tetanu and Lovono (also nearly extinct) — three languages dying in one small place.",
    coordinates: { lat: -11.66, lng: 166.85 },
  },
  {
    name: "Njerep",
    region: "Adamawa",
    country: "Cameroon / Nigeria",
    speakers: "~4",
    status: "critically_endangered",
    family: "Niger-Congo (Bantoid)",
    uniqueFeature: "Remaining speakers are all elderly and now use Mambila as their primary language; Njerep survives only in songs and rituals.",
    coordinates: { lat: 6.84, lng: 11.23 },
  },
  {
    name: "Liki",
    region: "Sarmi Regency, Papua",
    country: "Indonesia",
    speakers: "~11",
    status: "critically_endangered",
    family: "Austronesian",
    uniqueFeature: "Spoken on a tiny island; the community has shifted to Malay for economic reasons, leaving only elders fluent.",
    coordinates: { lat: -1.90, lng: 138.80 },
  },
  {
    name: "Kayardild",
    region: "Bentinck Island, Queensland",
    country: "Australia",
    speakers: "< 10",
    status: "critically_endangered",
    family: "Tangkic",
    uniqueFeature: "Has modal case — grammatical case marking that changes meaning based on tense and reality (did it happen, or is it hypothetical).",
    coordinates: { lat: -17.08, lng: 139.53 },
  },
  {
    name: "Warlpiri",
    region: "Northern Territory",
    country: "Australia",
    speakers: "~3,000",
    status: "vulnerable",
    family: "Pama-Nyungan",
    uniqueFeature: "Completely free word order — all grammatical roles are marked by suffixes, so words can appear in any sequence.",
    coordinates: { lat: -21.60, lng: 131.80 },
  },
  {
    name: "Kaurna",
    region: "Adelaide Plains",
    country: "Australia",
    speakers: "~50 (revived)",
    status: "dormant",
    family: "Pama-Nyungan",
    uniqueFeature: "Successfully revived from historical records after being dormant for over a century — now taught in schools near Adelaide.",
    coordinates: { lat: -34.93, lng: 138.60 },
  },
  {
    name: "Ngarrindjeri",
    region: "Lower Murray, South Australia",
    country: "Australia",
    speakers: "< 10 fluent",
    status: "critically_endangered",
    family: "Pama-Nyungan",
    uniqueFeature: "Contains a special register (women's language) used in certain ceremonial contexts — a built-in sociolinguistic layer.",
    coordinates: { lat: -35.43, lng: 139.00 },
  },
  {
    name: "Choctaw",
    region: "Oklahoma, Mississippi",
    country: "United States",
    speakers: "~9,600",
    status: "vulnerable",
    family: "Muskogean",
    uniqueFeature: "Used as a 'code talking' language in World War I — Choctaw soldiers transmitted military messages the enemy could not decipher.",
    coordinates: { lat: 34.77, lng: -96.68 },
  },
  {
    name: "Mapudungun",
    region: "Araucanía, Biobío",
    country: "Chile / Argentina",
    speakers: "~250,000",
    status: "vulnerable",
    family: "Isolate (Araucanian)",
    uniqueFeature: "A language isolate spoken by the Mapuche people who were never conquered by the Inca or the Spanish Crown; the language embodies centuries of resistance.",
    coordinates: { lat: -38.73, lng: -72.60 },
  },
  {
    name: "Tlingit",
    region: "Southeast Alaska",
    country: "United States",
    speakers: "~200",
    status: "critically_endangered",
    family: "Na-Dené",
    uniqueFeature: "Has ejective consonants produced with a simultaneous closure of the glottis — sounds that many English speakers find physically difficult to produce.",
    coordinates: { lat: 58.30, lng: -134.42 },
  },
  {
    name: "Michif",
    region: "Great Plains",
    country: "Canada / United States",
    speakers: "~700",
    status: "critically_endangered",
    family: "Mixed (Cree-French)",
    uniqueFeature: "A truly mixed language: Cree verbs with French nouns, each retaining their original grammar — a linguistic impossibility that exists.",
    coordinates: { lat: 51.15, lng: -106.67 },
  },
  {
    name: "Seri",
    region: "Sonora",
    country: "Mexico",
    speakers: "~900",
    status: "endangered",
    family: "Isolate",
    uniqueFeature: "A language isolate with an unusual 4-vowel system and positional verbs that change form based on the shape and position of objects.",
    coordinates: { lat: 28.88, lng: -111.97 },
  },
  {
    name: "Jingulu",
    region: "Northern Territory",
    country: "Australia",
    speakers: "~10",
    status: "critically_endangered",
    family: "Mirndi",
    uniqueFeature: "Has four grammatical genders: masculine, feminine, neuter, and vegetable — plants and plant products get their own gender.",
    coordinates: { lat: -16.70, lng: 135.97 },
  },
  {
    name: "Ts'ixa",
    region: "Nata River area",
    country: "Botswana",
    speakers: "~200",
    status: "critically_endangered",
    family: "Khoisan (Kx'a)",
    uniqueFeature: "One of the few remaining Kx'a family languages; its click consonant system is under rapid erosion as younger speakers simplify sounds.",
    coordinates: { lat: -20.22, lng: 26.23 },
  },
  {
    name: "Kusunda",
    region: "Western Nepal",
    country: "Nepal",
    speakers: "< 5",
    status: "critically_endangered",
    family: "Isolate",
    uniqueFeature: "A language isolate in the Himalayas with no proven relatives — may represent an ancient pre-migration language layer of South Asia.",
    coordinates: { lat: 28.17, lng: 82.15 },
  },
];

/**
 * Get endangered languages by status.
 */
export function getByStatus(
  status: EndangeredLanguage["status"]
): EndangeredLanguage[] {
  return endangeredLanguages.filter((l) => l.status === status);
}

/**
 * Get endangered languages by country.
 */
export function getByCountry(country: string): EndangeredLanguage[] {
  return endangeredLanguages.filter((l) =>
    l.country.toLowerCase().includes(country.toLowerCase())
  );
}
