export interface Language {
  code: string;
  name: string;
  nativeName: string;
  script: string;
  speakers: string;
  family: string;
  region: string;
  endangered: boolean;
  rtl: boolean;
}

export const languages: Language[] = [
  // --- Top 50 with full data ---
  { code: "en", name: "English", nativeName: "English", script: "Latin", speakers: "1.5 billion", family: "Germanic", region: "Global", endangered: false, rtl: false },
  { code: "es", name: "Spanish", nativeName: "Español", script: "Latin", speakers: "560 million", family: "Romance", region: "Europe / Americas", endangered: false, rtl: false },
  { code: "zh", name: "Mandarin Chinese", nativeName: "普通话", script: "Simplified Han", speakers: "1.1 billion", family: "Sino-Tibetan", region: "East Asia", endangered: false, rtl: false },
  { code: "hi", name: "Hindi", nativeName: "हिन्दी", script: "Devanagari", speakers: "610 million", family: "Indo-Aryan", region: "South Asia", endangered: false, rtl: false },
  { code: "ar", name: "Arabic", nativeName: "العربية", script: "Arabic", speakers: "420 million", family: "Semitic", region: "Middle East / North Africa", endangered: false, rtl: true },
  { code: "fr", name: "French", nativeName: "Français", script: "Latin", speakers: "310 million", family: "Romance", region: "Europe / Africa", endangered: false, rtl: false },
  { code: "bn", name: "Bengali", nativeName: "বাংলা", script: "Bengali", speakers: "270 million", family: "Indo-Aryan", region: "South Asia", endangered: false, rtl: false },
  { code: "pt", name: "Portuguese", nativeName: "Português", script: "Latin", speakers: "260 million", family: "Romance", region: "Europe / South America / Africa", endangered: false, rtl: false },
  { code: "ru", name: "Russian", nativeName: "Русский", script: "Cyrillic", speakers: "255 million", family: "Slavic", region: "Eastern Europe / Central Asia", endangered: false, rtl: false },
  { code: "ja", name: "Japanese", nativeName: "日本語", script: "Kanji / Hiragana / Katakana", speakers: "125 million", family: "Japonic", region: "East Asia", endangered: false, rtl: false },
  { code: "de", name: "German", nativeName: "Deutsch", script: "Latin", speakers: "135 million", family: "Germanic", region: "Central Europe", endangered: false, rtl: false },
  { code: "ko", name: "Korean", nativeName: "한국어", script: "Hangul", speakers: "82 million", family: "Koreanic", region: "East Asia", endangered: false, rtl: false },
  { code: "tr", name: "Turkish", nativeName: "Türkçe", script: "Latin", speakers: "85 million", family: "Turkic", region: "Western Asia / Southeast Europe", endangered: false, rtl: false },
  { code: "vi", name: "Vietnamese", nativeName: "Tiếng Việt", script: "Latin (Chữ Quốc Ngữ)", speakers: "85 million", family: "Austroasiatic", region: "Southeast Asia", endangered: false, rtl: false },
  { code: "it", name: "Italian", nativeName: "Italiano", script: "Latin", speakers: "68 million", family: "Romance", region: "Southern Europe", endangered: false, rtl: false },
  { code: "th", name: "Thai", nativeName: "ภาษาไทย", script: "Thai", speakers: "61 million", family: "Kra-Dai", region: "Southeast Asia", endangered: false, rtl: false },
  { code: "pl", name: "Polish", nativeName: "Polski", script: "Latin", speakers: "45 million", family: "Slavic", region: "Central Europe", endangered: false, rtl: false },
  { code: "uk", name: "Ukrainian", nativeName: "Українська", script: "Cyrillic", speakers: "45 million", family: "Slavic", region: "Eastern Europe", endangered: false, rtl: false },
  { code: "nl", name: "Dutch", nativeName: "Nederlands", script: "Latin", speakers: "30 million", family: "Germanic", region: "Western Europe", endangered: false, rtl: false },
  { code: "el", name: "Greek", nativeName: "Ελληνικά", script: "Greek", speakers: "13 million", family: "Hellenic", region: "Southeast Europe", endangered: false, rtl: false },
  { code: "he", name: "Hebrew", nativeName: "עברית", script: "Hebrew", speakers: "9 million", family: "Semitic", region: "Middle East", endangered: false, rtl: true },
  { code: "fa", name: "Farsi (Persian)", nativeName: "فارسی", script: "Arabic (Perso-Arabic)", speakers: "110 million", family: "Iranian", region: "Western Asia / Central Asia", endangered: false, rtl: true },
  { code: "ur", name: "Urdu", nativeName: "اردو", script: "Nastaliq (Perso-Arabic)", speakers: "230 million", family: "Indo-Aryan", region: "South Asia", endangered: false, rtl: true },
  { code: "sw", name: "Swahili", nativeName: "Kiswahili", script: "Latin", speakers: "100 million", family: "Bantu", region: "East Africa", endangered: false, rtl: false },
  { code: "ta", name: "Tamil", nativeName: "தமிழ்", script: "Tamil", speakers: "85 million", family: "Dravidian", region: "South Asia / Southeast Asia", endangered: false, rtl: false },
  { code: "te", name: "Telugu", nativeName: "తెలుగు", script: "Telugu", speakers: "96 million", family: "Dravidian", region: "South Asia", endangered: false, rtl: false },
  { code: "ms", name: "Malay", nativeName: "Bahasa Melayu", script: "Latin (Rumi)", speakers: "290 million", family: "Austronesian", region: "Southeast Asia", endangered: false, rtl: false },
  { code: "tl", name: "Tagalog", nativeName: "Tagalog", script: "Latin", speakers: "82 million", family: "Austronesian", region: "Southeast Asia", endangered: false, rtl: false },
  { code: "cs", name: "Czech", nativeName: "Čeština", script: "Latin", speakers: "13 million", family: "Slavic", region: "Central Europe", endangered: false, rtl: false },
  { code: "ro", name: "Romanian", nativeName: "Română", script: "Latin", speakers: "26 million", family: "Romance", region: "Southeast Europe", endangered: false, rtl: false },
  { code: "sv", name: "Swedish", nativeName: "Svenska", script: "Latin", speakers: "13 million", family: "Germanic", region: "Northern Europe", endangered: false, rtl: false },
  { code: "no", name: "Norwegian", nativeName: "Norsk", script: "Latin", speakers: "5.3 million", family: "Germanic", region: "Northern Europe", endangered: false, rtl: false },
  { code: "da", name: "Danish", nativeName: "Dansk", script: "Latin", speakers: "6 million", family: "Germanic", region: "Northern Europe", endangered: false, rtl: false },
  { code: "fi", name: "Finnish", nativeName: "Suomi", script: "Latin", speakers: "5.8 million", family: "Uralic", region: "Northern Europe", endangered: false, rtl: false },
  { code: "hu", name: "Hungarian", nativeName: "Magyar", script: "Latin", speakers: "13 million", family: "Uralic", region: "Central Europe", endangered: false, rtl: false },
  { code: "id", name: "Indonesian", nativeName: "Bahasa Indonesia", script: "Latin", speakers: "200 million", family: "Austronesian", region: "Southeast Asia", endangered: false, rtl: false },
  { code: "ca", name: "Catalan", nativeName: "Català", script: "Latin", speakers: "10 million", family: "Romance", region: "Southern Europe", endangered: false, rtl: false },
  { code: "my", name: "Burmese", nativeName: "မြန်မာစာ", script: "Mon", speakers: "43 million", family: "Sino-Tibetan", region: "Southeast Asia", endangered: false, rtl: false },
  { code: "km", name: "Khmer", nativeName: "ភាសាខ្មែរ", script: "Khmer", speakers: "18 million", family: "Austroasiatic", region: "Southeast Asia", endangered: false, rtl: false },
  { code: "lo", name: "Lao", nativeName: "ພາສາລາວ", script: "Lao", speakers: "30 million", family: "Kra-Dai", region: "Southeast Asia", endangered: false, rtl: false },
  { code: "ne", name: "Nepali", nativeName: "नेपाली", script: "Devanagari", speakers: "32 million", family: "Indo-Aryan", region: "South Asia", endangered: false, rtl: false },
  { code: "si", name: "Sinhala", nativeName: "සිංහල", script: "Sinhala", speakers: "17 million", family: "Indo-Aryan", region: "South Asia", endangered: false, rtl: false },
  { code: "am", name: "Amharic", nativeName: "አማርኛ", script: "Ge'ez (Ethiopic)", speakers: "57 million", family: "Semitic", region: "East Africa", endangered: false, rtl: false },
  { code: "yo", name: "Yoruba", nativeName: "Yorùbá", script: "Latin", speakers: "50 million", family: "Niger-Congo", region: "West Africa", endangered: false, rtl: false },
  { code: "ig", name: "Igbo", nativeName: "Igbo", script: "Latin", speakers: "45 million", family: "Niger-Congo", region: "West Africa", endangered: false, rtl: false },
  { code: "zu", name: "Zulu", nativeName: "isiZulu", script: "Latin", speakers: "28 million", family: "Bantu", region: "Southern Africa", endangered: false, rtl: false },
  { code: "ha", name: "Hausa", nativeName: "Hausa", script: "Latin / Ajami", speakers: "80 million", family: "Afroasiatic", region: "West Africa", endangered: false, rtl: false },
  { code: "so", name: "Somali", nativeName: "Soomaali", script: "Latin (Osmanya historic)", speakers: "22 million", family: "Afroasiatic", region: "East Africa", endangered: false, rtl: false },
  { code: "ps", name: "Pashto", nativeName: "پښتو", script: "Arabic (Pashto variant)", speakers: "60 million", family: "Iranian", region: "Central/South Asia", endangered: false, rtl: true },
  { code: "pa", name: "Punjabi", nativeName: "ਪੰਜਾਬੀ", script: "Gurmukhi / Shahmukhi", speakers: "150 million", family: "Indo-Aryan", region: "South Asia", endangered: false, rtl: false },

  // --- 150 additional languages (basic entries) ---
  { code: "af", name: "Afrikaans", nativeName: "Afrikaans", script: "Latin", speakers: "7.2 million", family: "Germanic", region: "Southern Africa", endangered: false, rtl: false },
  { code: "sq", name: "Albanian", nativeName: "Shqip", script: "Latin", speakers: "7.5 million", family: "Albanian", region: "Southeast Europe", endangered: false, rtl: false },
  { code: "hy", name: "Armenian", nativeName: "Հայերեն", script: "Armenian", speakers: "6.7 million", family: "Armenian", region: "Western Asia", endangered: false, rtl: false },
  { code: "az", name: "Azerbaijani", nativeName: "Azərbaycan dili", script: "Latin", speakers: "23 million", family: "Turkic", region: "Western Asia", endangered: false, rtl: false },
  { code: "eu", name: "Basque", nativeName: "Euskara", script: "Latin", speakers: "750,000", family: "Isolate", region: "Western Europe", endangered: false, rtl: false },
  { code: "be", name: "Belarusian", nativeName: "Беларуская", script: "Cyrillic", speakers: "5.1 million", family: "Slavic", region: "Eastern Europe", endangered: false, rtl: false },
  { code: "bs", name: "Bosnian", nativeName: "Bosanski", script: "Latin / Cyrillic", speakers: "2.5 million", family: "Slavic", region: "Southeast Europe", endangered: false, rtl: false },
  { code: "bg", name: "Bulgarian", nativeName: "Български", script: "Cyrillic", speakers: "8 million", family: "Slavic", region: "Southeast Europe", endangered: false, rtl: false },
  { code: "ceb", name: "Cebuano", nativeName: "Sinugbuanon", script: "Latin", speakers: "27 million", family: "Austronesian", region: "Southeast Asia", endangered: false, rtl: false },
  { code: "ny", name: "Chichewa", nativeName: "Chicheŵa", script: "Latin", speakers: "12 million", family: "Bantu", region: "Southern Africa", endangered: false, rtl: false },
  { code: "zh-TW", name: "Chinese (Traditional)", nativeName: "繁體中文", script: "Traditional Han", speakers: "25 million", family: "Sino-Tibetan", region: "East Asia", endangered: false, rtl: false },
  { code: "co", name: "Corsican", nativeName: "Corsu", script: "Latin", speakers: "150,000", family: "Romance", region: "Southern Europe", endangered: false, rtl: false },
  { code: "hr", name: "Croatian", nativeName: "Hrvatski", script: "Latin", speakers: "5.6 million", family: "Slavic", region: "Southeast Europe", endangered: false, rtl: false },
  { code: "eo", name: "Esperanto", nativeName: "Esperanto", script: "Latin", speakers: "2 million", family: "Constructed", region: "Global", endangered: false, rtl: false },
  { code: "et", name: "Estonian", nativeName: "Eesti", script: "Latin", speakers: "1.1 million", family: "Uralic", region: "Northern Europe", endangered: false, rtl: false },
  { code: "fj", name: "Fijian", nativeName: "Vosa Vakaviti", script: "Latin", speakers: "340,000", family: "Austronesian", region: "Oceania", endangered: false, rtl: false },
  { code: "gl", name: "Galician", nativeName: "Galego", script: "Latin", speakers: "2.4 million", family: "Romance", region: "Southern Europe", endangered: false, rtl: false },
  { code: "ka", name: "Georgian", nativeName: "ქართული", script: "Georgian (Mkhedruli)", speakers: "3.7 million", family: "Kartvelian", region: "Western Asia", endangered: false, rtl: false },
  { code: "gu", name: "Gujarati", nativeName: "ગુજરાતી", script: "Gujarati", speakers: "57 million", family: "Indo-Aryan", region: "South Asia", endangered: false, rtl: false },
  { code: "ht", name: "Haitian Creole", nativeName: "Kreyòl Ayisyen", script: "Latin", speakers: "12 million", family: "French Creole", region: "Caribbean", endangered: false, rtl: false },
  { code: "haw", name: "Hawaiian", nativeName: "ʻŌlelo Hawaiʻi", script: "Latin", speakers: "24,000", family: "Austronesian", region: "Oceania", endangered: false, rtl: false },
  { code: "hmn", name: "Hmong", nativeName: "Hmoob", script: "Latin (RPA)", speakers: "4 million", family: "Hmong-Mien", region: "East/Southeast Asia", endangered: false, rtl: false },
  { code: "is", name: "Icelandic", nativeName: "Íslenska", script: "Latin", speakers: "360,000", family: "Germanic", region: "Northern Europe", endangered: false, rtl: false },
  { code: "ga", name: "Irish", nativeName: "Gaeilge", script: "Latin", speakers: "1.7 million", family: "Celtic", region: "Western Europe", endangered: false, rtl: false },
  { code: "jv", name: "Javanese", nativeName: "Basa Jawa", script: "Latin / Javanese", speakers: "82 million", family: "Austronesian", region: "Southeast Asia", endangered: false, rtl: false },
  { code: "kn", name: "Kannada", nativeName: "ಕನ್ನಡ", script: "Kannada", speakers: "51 million", family: "Dravidian", region: "South Asia", endangered: false, rtl: false },
  { code: "kk", name: "Kazakh", nativeName: "Қазақ тілі", script: "Cyrillic / Latin", speakers: "13 million", family: "Turkic", region: "Central Asia", endangered: false, rtl: false },
  { code: "rw", name: "Kinyarwanda", nativeName: "Ikinyarwanda", script: "Latin", speakers: "12 million", family: "Bantu", region: "East Africa", endangered: false, rtl: false },
  { code: "ky", name: "Kyrgyz", nativeName: "Кыргызча", script: "Cyrillic", speakers: "4.5 million", family: "Turkic", region: "Central Asia", endangered: false, rtl: false },
  { code: "ku", name: "Kurdish", nativeName: "Kurdî", script: "Latin / Arabic", speakers: "30 million", family: "Iranian", region: "Western Asia", endangered: false, rtl: false },
  { code: "la", name: "Latin", nativeName: "Latina", script: "Latin", speakers: "0 (liturgical)", family: "Italic", region: "Europe (historical)", endangered: false, rtl: false },
  { code: "lv", name: "Latvian", nativeName: "Latviešu", script: "Latin", speakers: "1.7 million", family: "Baltic", region: "Northern Europe", endangered: false, rtl: false },
  { code: "lt", name: "Lithuanian", nativeName: "Lietuvių", script: "Latin", speakers: "2.8 million", family: "Baltic", region: "Northern Europe", endangered: false, rtl: false },
  { code: "lb", name: "Luxembourgish", nativeName: "Lëtzebuergesch", script: "Latin", speakers: "400,000", family: "Germanic", region: "Western Europe", endangered: false, rtl: false },
  { code: "mk", name: "Macedonian", nativeName: "Македонски", script: "Cyrillic", speakers: "2 million", family: "Slavic", region: "Southeast Europe", endangered: false, rtl: false },
  { code: "mg", name: "Malagasy", nativeName: "Malagasy", script: "Latin", speakers: "25 million", family: "Austronesian", region: "East Africa", endangered: false, rtl: false },
  { code: "ml", name: "Malayalam", nativeName: "മലയാളം", script: "Malayalam", speakers: "38 million", family: "Dravidian", region: "South Asia", endangered: false, rtl: false },
  { code: "mt", name: "Maltese", nativeName: "Malti", script: "Latin", speakers: "520,000", family: "Semitic", region: "Southern Europe", endangered: false, rtl: false },
  { code: "mi", name: "Maori", nativeName: "Te Reo Māori", script: "Latin", speakers: "185,000", family: "Austronesian", region: "Oceania", endangered: false, rtl: false },
  { code: "mr", name: "Marathi", nativeName: "मराठी", script: "Devanagari", speakers: "99 million", family: "Indo-Aryan", region: "South Asia", endangered: false, rtl: false },
  { code: "mn", name: "Mongolian", nativeName: "Монгол", script: "Cyrillic / Mongolian", speakers: "5.2 million", family: "Mongolic", region: "Central Asia", endangered: false, rtl: false },
  { code: "or", name: "Odia", nativeName: "ଓଡ଼ିଆ", script: "Odia", speakers: "38 million", family: "Indo-Aryan", region: "South Asia", endangered: false, rtl: false },
  { code: "om", name: "Oromo", nativeName: "Afaan Oromoo", script: "Latin (Qubee)", speakers: "37 million", family: "Afroasiatic", region: "East Africa", endangered: false, rtl: false },
  { code: "sr", name: "Serbian", nativeName: "Српски", script: "Cyrillic / Latin", speakers: "12 million", family: "Slavic", region: "Southeast Europe", endangered: false, rtl: false },
  { code: "sn", name: "Shona", nativeName: "ChiShona", script: "Latin", speakers: "15 million", family: "Bantu", region: "Southern Africa", endangered: false, rtl: false },
  { code: "sd", name: "Sindhi", nativeName: "سنڌي", script: "Arabic (Sindhi variant)", speakers: "32 million", family: "Indo-Aryan", region: "South Asia", endangered: false, rtl: true },
  { code: "sk", name: "Slovak", nativeName: "Slovenčina", script: "Latin", speakers: "5.6 million", family: "Slavic", region: "Central Europe", endangered: false, rtl: false },
  { code: "sl", name: "Slovenian", nativeName: "Slovenščina", script: "Latin", speakers: "2.5 million", family: "Slavic", region: "Central Europe", endangered: false, rtl: false },
  { code: "st", name: "Sesotho", nativeName: "Sesotho", script: "Latin", speakers: "14 million", family: "Bantu", region: "Southern Africa", endangered: false, rtl: false },
  { code: "su", name: "Sundanese", nativeName: "Basa Sunda", script: "Latin / Sundanese", speakers: "42 million", family: "Austronesian", region: "Southeast Asia", endangered: false, rtl: false },
  { code: "tg", name: "Tajik", nativeName: "Тоҷикӣ", script: "Cyrillic", speakers: "8.4 million", family: "Iranian", region: "Central Asia", endangered: false, rtl: false },
  { code: "tt", name: "Tatar", nativeName: "Татарча", script: "Cyrillic", speakers: "5.2 million", family: "Turkic", region: "Eastern Europe", endangered: false, rtl: false },
  { code: "ti", name: "Tigrinya", nativeName: "ትግርኛ", script: "Ge'ez (Ethiopic)", speakers: "9 million", family: "Semitic", region: "East Africa", endangered: false, rtl: false },
  { code: "tk", name: "Turkmen", nativeName: "Türkmençe", script: "Latin", speakers: "7.5 million", family: "Turkic", region: "Central Asia", endangered: false, rtl: false },
  { code: "ug", name: "Uyghur", nativeName: "ئۇيغۇرچە", script: "Arabic (Uyghur variant)", speakers: "10 million", family: "Turkic", region: "Central Asia", endangered: false, rtl: true },
  { code: "uz", name: "Uzbek", nativeName: "Oʻzbek", script: "Latin / Cyrillic", speakers: "34 million", family: "Turkic", region: "Central Asia", endangered: false, rtl: false },
  { code: "cy", name: "Welsh", nativeName: "Cymraeg", script: "Latin", speakers: "880,000", family: "Celtic", region: "Western Europe", endangered: false, rtl: false },
  { code: "xh", name: "Xhosa", nativeName: "isiXhosa", script: "Latin", speakers: "19 million", family: "Bantu", region: "Southern Africa", endangered: false, rtl: false },
  { code: "yi", name: "Yiddish", nativeName: "ייִדיש", script: "Hebrew", speakers: "1.5 million", family: "Germanic", region: "Global (diaspora)", endangered: false, rtl: true },
  { code: "wo", name: "Wolof", nativeName: "Wolof", script: "Latin", speakers: "12 million", family: "Niger-Congo", region: "West Africa", endangered: false, rtl: false },
  { code: "fy", name: "Frisian", nativeName: "Frysk", script: "Latin", speakers: "500,000", family: "Germanic", region: "Western Europe", endangered: false, rtl: false },
  { code: "gd", name: "Scottish Gaelic", nativeName: "Gàidhlig", script: "Latin", speakers: "57,000", family: "Celtic", region: "Western Europe", endangered: false, rtl: false },
  { code: "sm", name: "Samoan", nativeName: "Gagana Samoa", script: "Latin", speakers: "510,000", family: "Austronesian", region: "Oceania", endangered: false, rtl: false },
  { code: "to", name: "Tongan", nativeName: "Lea Fakatonga", script: "Latin", speakers: "187,000", family: "Austronesian", region: "Oceania", endangered: false, rtl: false },
  { code: "ts", name: "Tsonga", nativeName: "Xitsonga", script: "Latin", speakers: "12 million", family: "Bantu", region: "Southern Africa", endangered: false, rtl: false },
  { code: "tn", name: "Tswana", nativeName: "Setswana", script: "Latin", speakers: "14 million", family: "Bantu", region: "Southern Africa", endangered: false, rtl: false },
  { code: "tw", name: "Twi", nativeName: "Twi", script: "Latin", speakers: "9 million", family: "Niger-Congo", region: "West Africa", endangered: false, rtl: false },
  { code: "ve", name: "Venda", nativeName: "Tshivenḓa", script: "Latin", speakers: "1.3 million", family: "Bantu", region: "Southern Africa", endangered: false, rtl: false },
  { code: "war", name: "Waray", nativeName: "Winaray", script: "Latin", speakers: "3.6 million", family: "Austronesian", region: "Southeast Asia", endangered: false, rtl: false },
  { code: "as", name: "Assamese", nativeName: "অসমীয়া", script: "Assamese", speakers: "25 million", family: "Indo-Aryan", region: "South Asia", endangered: false, rtl: false },
  { code: "ay", name: "Aymara", nativeName: "Aymar aru", script: "Latin", speakers: "1.7 million", family: "Aymaran", region: "South America", endangered: false, rtl: false },
  { code: "bm", name: "Bambara", nativeName: "Bamanankan", script: "Latin / N'Ko", speakers: "14 million", family: "Mande", region: "West Africa", endangered: false, rtl: false },
  { code: "bho", name: "Bhojpuri", nativeName: "भोजपुरी", script: "Devanagari", speakers: "52 million", family: "Indo-Aryan", region: "South Asia", endangered: false, rtl: false },
  { code: "dz", name: "Dzongkha", nativeName: "རྫོང་ཁ", script: "Tibetan", speakers: "640,000", family: "Sino-Tibetan", region: "South Asia", endangered: false, rtl: false },
  { code: "ee", name: "Ewe", nativeName: "Eʋegbe", script: "Latin", speakers: "7 million", family: "Niger-Congo", region: "West Africa", endangered: false, rtl: false },
  { code: "fo", name: "Faroese", nativeName: "Føroyskt", script: "Latin", speakers: "72,000", family: "Germanic", region: "Northern Europe", endangered: false, rtl: false },
  { code: "ff", name: "Fula", nativeName: "Fulfulde", script: "Latin / Adlam", speakers: "40 million", family: "Niger-Congo", region: "West Africa", endangered: false, rtl: false },
  { code: "gn", name: "Guarani", nativeName: "Avañeʼẽ", script: "Latin", speakers: "7 million", family: "Tupi-Guarani", region: "South America", endangered: false, rtl: false },
  { code: "ii", name: "Yi", nativeName: "ꆈꌠꉙ", script: "Yi", speakers: "7.8 million", family: "Sino-Tibetan", region: "East Asia", endangered: false, rtl: false },
  { code: "ilo", name: "Ilocano", nativeName: "Ilokano", script: "Latin", speakers: "10 million", family: "Austronesian", region: "Southeast Asia", endangered: false, rtl: false },
  { code: "kr", name: "Kanuri", nativeName: "Kànùrí", script: "Latin / Arabic", speakers: "10 million", family: "Saharan", region: "Central Africa", endangered: false, rtl: false },
  { code: "ks", name: "Kashmiri", nativeName: "कॉशुर", script: "Devanagari / Perso-Arabic", speakers: "7 million", family: "Indo-Aryan", region: "South Asia", endangered: false, rtl: false },
  { code: "lg", name: "Luganda", nativeName: "Oluganda", script: "Latin", speakers: "10 million", family: "Bantu", region: "East Africa", endangered: false, rtl: false },
  { code: "ln", name: "Lingala", nativeName: "Lingála", script: "Latin", speakers: "45 million", family: "Bantu", region: "Central Africa", endangered: false, rtl: false },
  { code: "mai", name: "Maithili", nativeName: "मैथिली", script: "Devanagari", speakers: "34 million", family: "Indo-Aryan", region: "South Asia", endangered: false, rtl: false },
  { code: "mni", name: "Meitei", nativeName: "মৈতৈলোন্", script: "Meitei Mayek", speakers: "1.8 million", family: "Sino-Tibetan", region: "South Asia", endangered: false, rtl: false },
  { code: "nso", name: "Northern Sotho", nativeName: "Sesotho sa Leboa", script: "Latin", speakers: "4.7 million", family: "Bantu", region: "Southern Africa", endangered: false, rtl: false },
  { code: "oc", name: "Occitan", nativeName: "Occitan", script: "Latin", speakers: "800,000", family: "Romance", region: "Southern Europe", endangered: false, rtl: false },
  { code: "qu", name: "Quechua", nativeName: "Runa Simi", script: "Latin", speakers: "10 million", family: "Quechuan", region: "South America", endangered: false, rtl: false },
  { code: "rm", name: "Romansh", nativeName: "Rumantsch", script: "Latin", speakers: "40,000", family: "Romance", region: "Central Europe", endangered: false, rtl: false },
  { code: "rn", name: "Kirundi", nativeName: "Ikirundi", script: "Latin", speakers: "12 million", family: "Bantu", region: "East Africa", endangered: false, rtl: false },
  { code: "sa", name: "Sanskrit", nativeName: "संस्कृतम्", script: "Devanagari", speakers: "25,000 (fluent)", family: "Indo-Aryan", region: "South Asia", endangered: false, rtl: false },
  { code: "sc", name: "Sardinian", nativeName: "Sardu", script: "Latin", speakers: "1 million", family: "Romance", region: "Southern Europe", endangered: false, rtl: false },
  { code: "ss", name: "Swazi", nativeName: "SiSwati", script: "Latin", speakers: "2.4 million", family: "Bantu", region: "Southern Africa", endangered: false, rtl: false },
  { code: "bo", name: "Tibetan", nativeName: "བོད་སྐད་", script: "Tibetan", speakers: "6 million", family: "Sino-Tibetan", region: "Central Asia", endangered: false, rtl: false },
  { code: "nah", name: "Nahuatl", nativeName: "Nāhuatl", script: "Latin", speakers: "1.7 million", family: "Uto-Aztecan", region: "North America", endangered: false, rtl: false },
  { code: "chr", name: "Cherokee", nativeName: "ᏣᎳᎩ", script: "Cherokee syllabary", speakers: "2,000", family: "Iroquoian", region: "North America", endangered: false, rtl: false },
  { code: "nv", name: "Navajo", nativeName: "Diné bizaad", script: "Latin", speakers: "170,000", family: "Athabaskan", region: "North America", endangered: false, rtl: false },
  { code: "cr", name: "Cree", nativeName: "ᓀᐦᐃᔭᐍᐏᐣ", script: "Cree syllabics / Latin", speakers: "96,000", family: "Algonquian", region: "North America", endangered: false, rtl: false },
  { code: "oj", name: "Ojibwe", nativeName: "Anishinaabemowin", script: "Latin / Syllabics", speakers: "50,000", family: "Algonquian", region: "North America", endangered: false, rtl: false },
  { code: "ty", name: "Tahitian", nativeName: "Reo Tahiti", script: "Latin", speakers: "68,000", family: "Austronesian", region: "Oceania", endangered: false, rtl: false },
  { code: "tkl", name: "Tokelauan", nativeName: "Te Gagana Tokelau", script: "Latin", speakers: "4,500", family: "Austronesian", region: "Oceania", endangered: false, rtl: false },
  { code: "tvl", name: "Tuvaluan", nativeName: "Te Ggana Tuuvalu", script: "Latin", speakers: "11,000", family: "Austronesian", region: "Oceania", endangered: false, rtl: false },
  { code: "wls", name: "Wallisian", nativeName: "Fakaʻuvea", script: "Latin", speakers: "10,000", family: "Austronesian", region: "Oceania", endangered: false, rtl: false },
  { code: "rap", name: "Rapa Nui", nativeName: "Vananga Rapa Nui", script: "Latin", speakers: "3,700", family: "Austronesian", region: "Oceania", endangered: false, rtl: false },
  { code: "mh", name: "Marshallese", nativeName: "Kajin M̧ajeļ", script: "Latin", speakers: "55,000", family: "Austronesian", region: "Oceania", endangered: false, rtl: false },
  { code: "pau", name: "Palauan", nativeName: "A Tekoi er a Belau", script: "Latin", speakers: "18,000", family: "Austronesian", region: "Oceania", endangered: false, rtl: false },
  { code: "niu", name: "Niuean", nativeName: "Ko e vagahau Niuē", script: "Latin", speakers: "8,000", family: "Austronesian", region: "Oceania", endangered: false, rtl: false },
  { code: "rar", name: "Cook Islands Maori", nativeName: "Te Reo Māori Kūki 'Āirani", script: "Latin", speakers: "13,000", family: "Austronesian", region: "Oceania", endangered: false, rtl: false },
  { code: "chm", name: "Mari", nativeName: "Марий йылме", script: "Cyrillic", speakers: "400,000", family: "Uralic", region: "Eastern Europe", endangered: false, rtl: false },
  { code: "udm", name: "Udmurt", nativeName: "Удмурт кыл", script: "Cyrillic", speakers: "340,000", family: "Uralic", region: "Eastern Europe", endangered: false, rtl: false },
  { code: "kv", name: "Komi", nativeName: "Коми кыв", script: "Cyrillic", speakers: "220,000", family: "Uralic", region: "Eastern Europe", endangered: false, rtl: false },
  { code: "mdf", name: "Moksha", nativeName: "Мокшень кяль", script: "Cyrillic", speakers: "250,000", family: "Uralic", region: "Eastern Europe", endangered: false, rtl: false },
  { code: "myv", name: "Erzya", nativeName: "Эрзянь кель", script: "Cyrillic", speakers: "310,000", family: "Uralic", region: "Eastern Europe", endangered: false, rtl: false },
  { code: "sah", name: "Yakut", nativeName: "Саха тыла", script: "Cyrillic", speakers: "450,000", family: "Turkic", region: "North Asia", endangered: false, rtl: false },
  { code: "cv", name: "Chuvash", nativeName: "Чӑвашла", script: "Cyrillic", speakers: "1 million", family: "Turkic", region: "Eastern Europe", endangered: false, rtl: false },
  { code: "ba", name: "Bashkir", nativeName: "Башҡортса", script: "Cyrillic", speakers: "1.2 million", family: "Turkic", region: "Eastern Europe", endangered: false, rtl: false },
  { code: "ce", name: "Chechen", nativeName: "Нохчийн мотт", script: "Cyrillic", speakers: "2 million", family: "Northeast Caucasian", region: "Western Asia", endangered: false, rtl: false },
  { code: "av", name: "Avar", nativeName: "Магӏарул мацӏ", script: "Cyrillic", speakers: "760,000", family: "Northeast Caucasian", region: "Western Asia", endangered: false, rtl: false },
  { code: "lez", name: "Lezgin", nativeName: "Лезги чӏал", script: "Cyrillic", speakers: "800,000", family: "Northeast Caucasian", region: "Western Asia", endangered: false, rtl: false },
  { code: "inh", name: "Ingush", nativeName: "ГӀалгӀай мотт", script: "Cyrillic", speakers: "500,000", family: "Northeast Caucasian", region: "Western Asia", endangered: false, rtl: false },
  { code: "os", name: "Ossetian", nativeName: "Ирон æвзаг", script: "Cyrillic", speakers: "600,000", family: "Iranian", region: "Western Asia", endangered: false, rtl: false },
  { code: "ab", name: "Abkhaz", nativeName: "Аҧсуа бызшәа", script: "Cyrillic", speakers: "190,000", family: "Northwest Caucasian", region: "Western Asia", endangered: false, rtl: false },
  { code: "ady", name: "Adyghe", nativeName: "Адыгабзэ", script: "Cyrillic", speakers: "590,000", family: "Northwest Caucasian", region: "Western Asia", endangered: false, rtl: false },
  { code: "kbd", name: "Kabardian", nativeName: "Адыгэбзэ", script: "Cyrillic", speakers: "1.6 million", family: "Northwest Caucasian", region: "Western Asia", endangered: false, rtl: false },
  { code: "tab", name: "Tabasaran", nativeName: "Табасаран чӀал", script: "Cyrillic", speakers: "150,000", family: "Northeast Caucasian", region: "Western Asia", endangered: false, rtl: false },
  { code: "nog", name: "Nogai", nativeName: "Ногай тили", script: "Cyrillic", speakers: "90,000", family: "Turkic", region: "Western Asia", endangered: false, rtl: false },
  { code: "kum", name: "Kumyk", nativeName: "Къумукъ тил", script: "Cyrillic", speakers: "500,000", family: "Turkic", region: "Western Asia", endangered: false, rtl: false },
  { code: "krc", name: "Karachay-Balkar", nativeName: "Къарачай-малкъар тил", script: "Cyrillic", speakers: "400,000", family: "Turkic", region: "Western Asia", endangered: false, rtl: false },
  { code: "tyv", name: "Tuvan", nativeName: "Тыва дыл", script: "Cyrillic", speakers: "280,000", family: "Turkic", region: "Central Asia", endangered: false, rtl: false },
  { code: "alt", name: "Altai", nativeName: "Алтай тил", script: "Cyrillic", speakers: "55,000", family: "Turkic", region: "Central Asia", endangered: false, rtl: false },
  { code: "kjh", name: "Khakas", nativeName: "Хакас тілі", script: "Cyrillic", speakers: "43,000", family: "Turkic", region: "North Asia", endangered: false, rtl: false },
  { code: "bua", name: "Buryat", nativeName: "Буряад хэлэн", script: "Cyrillic", speakers: "265,000", family: "Mongolic", region: "North Asia", endangered: false, rtl: false },
  { code: "xal", name: "Kalmyk", nativeName: "Хальмг келн", script: "Cyrillic", speakers: "80,000", family: "Mongolic", region: "Eastern Europe", endangered: false, rtl: false },
  { code: "evn", name: "Evenki", nativeName: "Эвэды̄ турэ̄н", script: "Cyrillic", speakers: "16,000", family: "Tungusic", region: "North Asia", endangered: false, rtl: false },
  { code: "eve", name: "Even", nativeName: "Эвэн торэн", script: "Cyrillic", speakers: "5,700", family: "Tungusic", region: "North Asia", endangered: false, rtl: false },
  { code: "ckt", name: "Chukchi", nativeName: "Ԓыгъоравэтԓьэн", script: "Cyrillic", speakers: "5,000", family: "Chukotko-Kamchatkan", region: "North Asia", endangered: false, rtl: false },
  { code: "yrk", name: "Nenets", nativeName: "Ненэцяʼ вада", script: "Cyrillic", speakers: "22,000", family: "Uralic", region: "North Asia", endangered: false, rtl: false },
  { code: "sel", name: "Selkup", nativeName: "Шёльӄумыт әты", script: "Cyrillic", speakers: "1,000", family: "Uralic", region: "North Asia", endangered: false, rtl: false },
  { code: "kca", name: "Khanty", nativeName: "Ханты ясаӈ", script: "Cyrillic", speakers: "9,600", family: "Uralic", region: "North Asia", endangered: false, rtl: false },
  { code: "mns", name: "Mansi", nativeName: "Маньси лāтыӈ", script: "Cyrillic", speakers: "940", family: "Uralic", region: "North Asia", endangered: false, rtl: false },
];

/**
 * Get a language by its code.
 */
export function getLanguage(code: string): Language | undefined {
  return languages.find((l) => l.code === code);
}

/**
 * Get all RTL languages.
 */
export function getRtlLanguages(): Language[] {
  return languages.filter((l) => l.rtl);
}

/**
 * Search languages by name or native name.
 */
export function searchLanguages(query: string): Language[] {
  const q = query.toLowerCase();
  return languages.filter(
    (l) =>
      l.name.toLowerCase().includes(q) ||
      l.nativeName.toLowerCase().includes(q) ||
      l.code.toLowerCase() === q
  );
}
