export interface MedicalPhrase {
  id: string;
  english: string;
  category: string;
  critical: boolean;
  translations: Record<string, string>;
  pronunciationGuide?: Record<string, string>;
  culturalNote?: string;
}

export const medicalCategories = [
  "Emergency",
  "Symptoms",
  "Medications",
  "Procedures",
  "Consent",
  "Mental Health",
  "Pediatric",
  "Chronic Care",
] as const;

export type MedicalCategory = (typeof medicalCategories)[number];

export const medicalPhrases: MedicalPhrase[] = [
  // ============================================================
  // EMERGENCY (25+ phrases)
  // ============================================================
  {
    id: "em-001",
    english: "Can you hear me?",
    category: "Emergency",
    critical: true,
    translations: {
      es: "¿Puede oírme?",
      zh: "你能听到我说话吗？",
      ar: "هل تستطيع سماعي؟",
      fr: "Pouvez-vous m'entendre ?",
    },
    pronunciationGuide: {
      es: "PWEH-deh oh-EER-meh",
      zh: "nǐ néng tīng dào wǒ shuō huà ma",
      fr: "poo-VAY voo mahn-TAHN-druh",
    },
  },
  {
    id: "em-002",
    english: "Where does it hurt?",
    category: "Emergency",
    critical: true,
    translations: {
      es: "¿Dónde le duele?",
      zh: "哪里疼？",
      ar: "أين يؤلمك؟",
      fr: "Où avez-vous mal ?",
    },
    pronunciationGuide: {
      es: "DOHN-deh leh DWEH-leh",
      zh: "nǎ lǐ téng",
      fr: "oo ah-VAY voo MAL",
    },
  },
  {
    id: "em-003",
    english: "Are you allergic to any medications?",
    category: "Emergency",
    critical: true,
    translations: {
      es: "¿Es alérgico/a a algún medicamento?",
      zh: "你对任何药物过敏吗？",
      ar: "هل لديك حساسية من أي أدوية؟",
      fr: "Êtes-vous allergique à des médicaments ?",
    },
    culturalNote: "In Spanish, use 'alérgico' for male patients and 'alérgica' for female patients.",
  },
  {
    id: "em-004",
    english: "We need to take you to the hospital immediately.",
    category: "Emergency",
    critical: true,
    translations: {
      es: "Necesitamos llevarlo/a al hospital inmediatamente.",
      zh: "我们需要立刻送你去医院。",
      ar: "نحتاج أن ننقلك إلى المستشفى فوراً.",
      fr: "Nous devons vous emmener à l'hôpital immédiatement.",
    },
  },
  {
    id: "em-005",
    english: "Are you having trouble breathing?",
    category: "Emergency",
    critical: true,
    translations: {
      es: "¿Tiene dificultad para respirar?",
      zh: "你呼吸困难吗？",
      ar: "هل تواجه صعوبة في التنفس؟",
      fr: "Avez-vous des difficultés à respirer ?",
    },
  },
  {
    id: "em-006",
    english: "Do you have any medical conditions?",
    category: "Emergency",
    critical: true,
    translations: {
      es: "¿Tiene alguna condición médica?",
      zh: "你有什么疾病吗？",
      ar: "هل لديك أي حالات طبية؟",
      fr: "Avez-vous des antécédents médicaux ?",
    },
  },
  {
    id: "em-007",
    english: "When did the pain start?",
    category: "Emergency",
    critical: true,
    translations: {
      es: "¿Cuándo empezó el dolor?",
      zh: "疼痛是什么时候开始的？",
      ar: "متى بدأ الألم؟",
      fr: "Quand la douleur a-t-elle commencé ?",
    },
  },
  {
    id: "em-008",
    english: "I am going to give you an injection.",
    category: "Emergency",
    critical: true,
    translations: {
      es: "Voy a ponerle una inyección.",
      zh: "我要给你打一针。",
      ar: "سأعطيك حقنة.",
      fr: "Je vais vous faire une injection.",
    },
  },
  {
    id: "em-009",
    english: "Are you diabetic?",
    category: "Emergency",
    critical: true,
    translations: {
      es: "¿Es diabético/a?",
      zh: "你有糖尿病吗？",
      ar: "هل أنت مصاب بالسكري؟",
      fr: "Êtes-vous diabétique ?",
    },
  },
  {
    id: "em-010",
    english: "Do you take blood thinners?",
    category: "Emergency",
    critical: true,
    translations: {
      es: "¿Toma anticoagulantes?",
      zh: "你在服用血液稀释药物吗？",
      ar: "هل تتناول مميعات الدم؟",
      fr: "Prenez-vous des anticoagulants ?",
    },
  },
  {
    id: "em-011",
    english: "Can you move your fingers and toes?",
    category: "Emergency",
    critical: true,
    translations: {
      es: "¿Puede mover los dedos de las manos y los pies?",
      zh: "你能活动手指和脚趾吗？",
      ar: "هل تستطيع تحريك أصابع يديك وقدميك؟",
      fr: "Pouvez-vous bouger vos doigts et orteils ?",
    },
  },
  {
    id: "em-012",
    english: "Have you lost consciousness?",
    category: "Emergency",
    critical: true,
    translations: {
      es: "¿Ha perdido el conocimiento?",
      zh: "你失去过意识吗？",
      ar: "هل فقدت الوعي؟",
      fr: "Avez-vous perdu connaissance ?",
    },
  },
  {
    id: "em-013",
    english: "Do you have chest pain?",
    category: "Emergency",
    critical: true,
    translations: {
      es: "¿Tiene dolor en el pecho?",
      zh: "你胸口疼吗？",
      ar: "هل لديك ألم في الصدر؟",
      fr: "Avez-vous une douleur à la poitrine ?",
    },
  },
  {
    id: "em-014",
    english: "Please stay still. Do not move.",
    category: "Emergency",
    critical: true,
    translations: {
      es: "Por favor, quédese quieto/a. No se mueva.",
      zh: "请不要动。保持不动。",
      ar: "من فضلك ابقَ ثابتاً. لا تتحرك.",
      fr: "Veuillez rester immobile. Ne bougez pas.",
    },
  },
  {
    id: "em-015",
    english: "Is there someone we should call?",
    category: "Emergency",
    critical: false,
    translations: {
      es: "¿Hay alguien a quien debamos llamar?",
      zh: "有需要我们联系的人吗？",
      ar: "هل هناك شخص يجب أن نتصل به؟",
      fr: "Y a-t-il quelqu'un que nous devrions appeler ?",
    },
  },
  {
    id: "em-016",
    english: "How many fingers am I holding up?",
    category: "Emergency",
    critical: true,
    translations: {
      es: "¿Cuántos dedos estoy levantando?",
      zh: "我举了几根手指？",
      ar: "كم إصبعاً أرفع؟",
      fr: "Combien de doigts est-ce que je lève ?",
    },
  },
  {
    id: "em-017",
    english: "What is your blood type?",
    category: "Emergency",
    critical: true,
    translations: {
      es: "¿Cuál es su tipo de sangre?",
      zh: "你的血型是什么？",
      ar: "ما هي فصيلة دمك؟",
      fr: "Quel est votre groupe sanguin ?",
    },
  },
  {
    id: "em-018",
    english: "Are you pregnant?",
    category: "Emergency",
    critical: true,
    translations: {
      es: "¿Está embarazada?",
      zh: "你怀孕了吗？",
      ar: "هل أنتِ حامل؟",
      fr: "Êtes-vous enceinte ?",
    },
    culturalNote: "In many cultures, this is a very personal question. Ask with sensitivity and explain medical necessity.",
  },
  {
    id: "em-019",
    english: "We are going to start an IV.",
    category: "Emergency",
    critical: false,
    translations: {
      es: "Vamos a ponerle un suero intravenoso.",
      zh: "我们要给你输液。",
      ar: "سنبدأ بتركيب محلول وريدي.",
      fr: "Nous allons vous poser une perfusion.",
    },
  },
  {
    id: "em-020",
    english: "Rate your pain from 1 to 10.",
    category: "Emergency",
    critical: false,
    translations: {
      es: "Califique su dolor del 1 al 10.",
      zh: "请用1到10给你的疼痛打分。",
      ar: "قيّم ألمك من 1 إلى 10.",
      fr: "Évaluez votre douleur de 1 à 10.",
    },
  },
  {
    id: "em-021",
    english: "Have you eaten or drunk anything today?",
    category: "Emergency",
    critical: true,
    translations: {
      es: "¿Ha comido o bebido algo hoy?",
      zh: "你今天吃过或喝过什么吗？",
      ar: "هل أكلت أو شربت أي شيء اليوم؟",
      fr: "Avez-vous mangé ou bu quelque chose aujourd'hui ?",
    },
  },
  {
    id: "em-022",
    english: "Do you feel dizzy or nauseous?",
    category: "Emergency",
    critical: true,
    translations: {
      es: "¿Se siente mareado/a o con náuseas?",
      zh: "你感到头晕或恶心吗？",
      ar: "هل تشعر بالدوار أو الغثيان؟",
      fr: "Vous sentez-vous étourdi(e) ou nauséeux/nauséeuse ?",
    },
  },
  {
    id: "em-023",
    english: "We need to do a blood test.",
    category: "Emergency",
    critical: false,
    translations: {
      es: "Necesitamos hacerle un análisis de sangre.",
      zh: "我们需要做一个血液检测。",
      ar: "نحتاج إلى إجراء فحص دم.",
      fr: "Nous devons faire une analyse de sang.",
    },
  },
  {
    id: "em-024",
    english: "You are safe now.",
    category: "Emergency",
    critical: false,
    translations: {
      es: "Está a salvo ahora.",
      zh: "你现在安全了。",
      ar: "أنت بأمان الآن.",
      fr: "Vous êtes en sécurité maintenant.",
    },
  },
  {
    id: "em-025",
    english: "What medications are you currently taking?",
    category: "Emergency",
    critical: true,
    translations: {
      es: "¿Qué medicamentos está tomando actualmente?",
      zh: "你目前在服用什么药物？",
      ar: "ما الأدوية التي تتناولها حالياً؟",
      fr: "Quels médicaments prenez-vous actuellement ?",
    },
  },
  {
    id: "em-026",
    english: "Have you had any surgeries before?",
    category: "Emergency",
    critical: true,
    translations: {
      es: "¿Ha tenido alguna cirugía antes?",
      zh: "你以前做过手术吗？",
      ar: "هل أجريت أي عمليات جراحية من قبل؟",
      fr: "Avez-vous subi des opérations chirurgicales auparavant ?",
    },
  },

  // ============================================================
  // SYMPTOMS (25+ phrases)
  // ============================================================
  {
    id: "sy-001",
    english: "I have a headache.",
    category: "Symptoms",
    critical: false,
    translations: {
      es: "Tengo dolor de cabeza.",
      zh: "我头疼。",
      ar: "لدي صداع.",
      fr: "J'ai mal à la tête.",
    },
    pronunciationGuide: { es: "TEHN-goh doh-LOHR deh kah-BEH-sah" },
  },
  {
    id: "sy-002",
    english: "I have a fever.",
    category: "Symptoms",
    critical: false,
    translations: {
      es: "Tengo fiebre.",
      zh: "我发烧了。",
      ar: "لدي حمى.",
      fr: "J'ai de la fièvre.",
    },
  },
  {
    id: "sy-003",
    english: "I feel nauseous.",
    category: "Symptoms",
    critical: false,
    translations: {
      es: "Me siento con náuseas.",
      zh: "我感到恶心。",
      ar: "أشعر بالغثيان.",
      fr: "J'ai la nausée.",
    },
  },
  {
    id: "sy-004",
    english: "I have been vomiting.",
    category: "Symptoms",
    critical: false,
    translations: {
      es: "He estado vomitando.",
      zh: "我一直在呕吐。",
      ar: "كنت أتقيأ.",
      fr: "J'ai vomi.",
    },
  },
  {
    id: "sy-005",
    english: "I have diarrhea.",
    category: "Symptoms",
    critical: false,
    translations: {
      es: "Tengo diarrea.",
      zh: "我拉肚子。",
      ar: "لدي إسهال.",
      fr: "J'ai la diarrhée.",
    },
  },
  {
    id: "sy-006",
    english: "I am having difficulty swallowing.",
    category: "Symptoms",
    critical: true,
    translations: {
      es: "Tengo dificultad para tragar.",
      zh: "我吞咽困难。",
      ar: "أواجه صعوبة في البلع.",
      fr: "J'ai du mal à avaler.",
    },
  },
  {
    id: "sy-007",
    english: "My vision is blurry.",
    category: "Symptoms",
    critical: true,
    translations: {
      es: "Tengo la vista borrosa.",
      zh: "我视力模糊。",
      ar: "رؤيتي ضبابية.",
      fr: "Ma vision est floue.",
    },
  },
  {
    id: "sy-008",
    english: "I have a rash on my skin.",
    category: "Symptoms",
    critical: false,
    translations: {
      es: "Tengo un sarpullido en la piel.",
      zh: "我皮肤上有皮疹。",
      ar: "لدي طفح جلدي.",
      fr: "J'ai une éruption cutanée.",
    },
  },
  {
    id: "sy-009",
    english: "I feel numbness in my arm/leg.",
    category: "Symptoms",
    critical: true,
    translations: {
      es: "Siento entumecimiento en mi brazo/pierna.",
      zh: "我的手臂/腿感到麻木。",
      ar: "أشعر بتنميل في ذراعي/ساقي.",
      fr: "Je ressens un engourdissement dans mon bras/ma jambe.",
    },
    culturalNote: "Numbness combined with weakness may indicate stroke. Treat as critical.",
  },
  {
    id: "sy-010",
    english: "I have been coughing for more than a week.",
    category: "Symptoms",
    critical: false,
    translations: {
      es: "He estado tosiendo por más de una semana.",
      zh: "我咳嗽超过一周了。",
      ar: "أعاني من السعال منذ أكثر من أسبوع.",
      fr: "Je tousse depuis plus d'une semaine.",
    },
  },
  {
    id: "sy-011",
    english: "I have blood in my urine.",
    category: "Symptoms",
    critical: true,
    translations: {
      es: "Tengo sangre en la orina.",
      zh: "我的尿液中有血。",
      ar: "يوجد دم في بولي.",
      fr: "J'ai du sang dans mes urines.",
    },
  },
  {
    id: "sy-012",
    english: "I have a sharp pain in my abdomen.",
    category: "Symptoms",
    critical: true,
    translations: {
      es: "Tengo un dolor agudo en el abdomen.",
      zh: "我腹部有剧痛。",
      ar: "لدي ألم حاد في بطني.",
      fr: "J'ai une douleur vive dans l'abdomen.",
    },
  },
  {
    id: "sy-013",
    english: "I cannot sleep at night.",
    category: "Symptoms",
    critical: false,
    translations: {
      es: "No puedo dormir por la noche.",
      zh: "我晚上睡不着觉。",
      ar: "لا أستطيع النوم في الليل.",
      fr: "Je n'arrive pas à dormir la nuit.",
    },
  },
  {
    id: "sy-014",
    english: "I have lost my appetite.",
    category: "Symptoms",
    critical: false,
    translations: {
      es: "He perdido el apetito.",
      zh: "我没有食欲。",
      ar: "فقدت شهيتي.",
      fr: "J'ai perdu l'appétit.",
    },
  },
  {
    id: "sy-015",
    english: "I feel extremely tired all the time.",
    category: "Symptoms",
    critical: false,
    translations: {
      es: "Me siento extremadamente cansado/a todo el tiempo.",
      zh: "我一直感到极度疲倦。",
      ar: "أشعر بالتعب الشديد طوال الوقت.",
      fr: "Je me sens extrêmement fatigué(e) tout le temps.",
    },
  },
  {
    id: "sy-016",
    english: "I have swelling in my ankles.",
    category: "Symptoms",
    critical: false,
    translations: {
      es: "Tengo hinchazón en los tobillos.",
      zh: "我的脚踝肿了。",
      ar: "لدي تورم في كاحليّ.",
      fr: "J'ai un gonflement aux chevilles.",
    },
  },
  {
    id: "sy-017",
    english: "I have a burning sensation when I urinate.",
    category: "Symptoms",
    critical: false,
    translations: {
      es: "Siento ardor al orinar.",
      zh: "我排尿时有灼烧感。",
      ar: "أشعر بحرقة عند التبول.",
      fr: "J'ai une sensation de brûlure quand j'urine.",
    },
  },
  {
    id: "sy-018",
    english: "I am short of breath.",
    category: "Symptoms",
    critical: true,
    translations: {
      es: "Me falta el aire.",
      zh: "我呼吸急促。",
      ar: "أعاني من ضيق في التنفس.",
      fr: "J'ai le souffle court.",
    },
  },
  {
    id: "sy-019",
    english: "The pain is constant / comes and goes.",
    category: "Symptoms",
    critical: false,
    translations: {
      es: "El dolor es constante / va y viene.",
      zh: "疼痛是持续的 / 时有时无。",
      ar: "الألم مستمر / يأتي ويذهب.",
      fr: "La douleur est constante / va et vient.",
    },
  },
  {
    id: "sy-020",
    english: "I have been losing weight without trying.",
    category: "Symptoms",
    critical: true,
    translations: {
      es: "He estado perdiendo peso sin intentarlo.",
      zh: "我一直在无意中减轻体重。",
      ar: "أفقد وزني دون محاولة.",
      fr: "Je perds du poids sans le vouloir.",
    },
  },
  {
    id: "sy-021",
    english: "I feel a lump here.",
    category: "Symptoms",
    critical: true,
    translations: {
      es: "Siento un bulto aquí.",
      zh: "我在这里摸到一个肿块。",
      ar: "أشعر بكتلة هنا.",
      fr: "Je sens une grosseur ici.",
    },
  },
  {
    id: "sy-022",
    english: "I have pain in my joints.",
    category: "Symptoms",
    critical: false,
    translations: {
      es: "Tengo dolor en las articulaciones.",
      zh: "我关节疼痛。",
      ar: "لدي ألم في مفاصلي.",
      fr: "J'ai des douleurs articulaires.",
    },
  },
  {
    id: "sy-023",
    english: "I feel tightness in my chest.",
    category: "Symptoms",
    critical: true,
    translations: {
      es: "Siento opresión en el pecho.",
      zh: "我感到胸闷。",
      ar: "أشعر بضيق في صدري.",
      fr: "Je ressens une oppression dans la poitrine.",
    },
  },
  {
    id: "sy-024",
    english: "My ears are ringing.",
    category: "Symptoms",
    critical: false,
    translations: {
      es: "Me zumban los oídos.",
      zh: "我耳鸣。",
      ar: "أذناي تطنان.",
      fr: "J'ai des bourdonnements dans les oreilles.",
    },
  },
  {
    id: "sy-025",
    english: "I have a sore throat.",
    category: "Symptoms",
    critical: false,
    translations: {
      es: "Tengo dolor de garganta.",
      zh: "我喉咙疼。",
      ar: "لدي التهاب في الحلق.",
      fr: "J'ai mal à la gorge.",
    },
  },

  // ============================================================
  // MEDICATIONS (25+ phrases)
  // ============================================================
  {
    id: "md-001",
    english: "Take this medication with food.",
    category: "Medications",
    critical: false,
    translations: {
      es: "Tome este medicamento con comida.",
      zh: "请随餐服用此药。",
      ar: "تناول هذا الدواء مع الطعام.",
      fr: "Prenez ce médicament avec de la nourriture.",
    },
  },
  {
    id: "md-002",
    english: "Take one tablet twice a day.",
    category: "Medications",
    critical: true,
    translations: {
      es: "Tome una tableta dos veces al día.",
      zh: "每天服用两次，每次一片。",
      ar: "تناول قرصاً واحداً مرتين في اليوم.",
      fr: "Prenez un comprimé deux fois par jour.",
    },
  },
  {
    id: "md-003",
    english: "Do not take this medication on an empty stomach.",
    category: "Medications",
    critical: true,
    translations: {
      es: "No tome este medicamento con el estómago vacío.",
      zh: "不要空腹服用此药。",
      ar: "لا تتناول هذا الدواء على معدة فارغة.",
      fr: "Ne prenez pas ce médicament à jeun.",
    },
  },
  {
    id: "md-004",
    english: "This medication may cause drowsiness.",
    category: "Medications",
    critical: false,
    translations: {
      es: "Este medicamento puede causar somnolencia.",
      zh: "此药可能引起嗜睡。",
      ar: "قد يسبب هذا الدواء النعاس.",
      fr: "Ce médicament peut provoquer de la somnolence.",
    },
  },
  {
    id: "md-005",
    english: "Do not drink alcohol while taking this medication.",
    category: "Medications",
    critical: true,
    translations: {
      es: "No beba alcohol mientras toma este medicamento.",
      zh: "服用此药期间请勿饮酒。",
      ar: "لا تشرب الكحول أثناء تناول هذا الدواء.",
      fr: "Ne consommez pas d'alcool pendant la prise de ce médicament.",
    },
    culturalNote: "Be sensitive when discussing alcohol — some religions prohibit it and patients may be offended by the assumption.",
  },
  {
    id: "md-006",
    english: "You need to finish the full course of antibiotics.",
    category: "Medications",
    critical: true,
    translations: {
      es: "Necesita completar el curso completo de antibióticos.",
      zh: "你需要完成整个疗程的抗生素。",
      ar: "يجب عليك إكمال الجرعة الكاملة من المضادات الحيوية.",
      fr: "Vous devez terminer le traitement antibiotique complet.",
    },
  },
  {
    id: "md-007",
    english: "Store this medication in the refrigerator.",
    category: "Medications",
    critical: false,
    translations: {
      es: "Guarde este medicamento en el refrigerador.",
      zh: "请将此药存放在冰箱中。",
      ar: "احفظ هذا الدواء في الثلاجة.",
      fr: "Conservez ce médicament au réfrigérateur.",
    },
  },
  {
    id: "md-008",
    english: "Do not crush or chew this tablet.",
    category: "Medications",
    critical: true,
    translations: {
      es: "No triture ni mastique esta tableta.",
      zh: "请勿碾碎或咀嚼此药片。",
      ar: "لا تسحق أو تمضغ هذا القرص.",
      fr: "Ne pas écraser ou mâcher ce comprimé.",
    },
  },
  {
    id: "md-009",
    english: "Apply this cream to the affected area.",
    category: "Medications",
    critical: false,
    translations: {
      es: "Aplique esta crema en el área afectada.",
      zh: "将此药膏涂在患处。",
      ar: "ضع هذا الكريم على المنطقة المصابة.",
      fr: "Appliquez cette crème sur la zone affectée.",
    },
  },
  {
    id: "md-010",
    english: "This is a pain reliever.",
    category: "Medications",
    critical: false,
    translations: {
      es: "Este es un analgésico.",
      zh: "这是止痛药。",
      ar: "هذا مسكن للألم.",
      fr: "C'est un antidouleur.",
    },
  },
  {
    id: "md-011",
    english: "Take this medication before bedtime.",
    category: "Medications",
    critical: false,
    translations: {
      es: "Tome este medicamento antes de acostarse.",
      zh: "请在睡前服用此药。",
      ar: "تناول هذا الدواء قبل النوم.",
      fr: "Prenez ce médicament avant le coucher.",
    },
  },
  {
    id: "md-012",
    english: "Your prescription is ready.",
    category: "Medications",
    critical: false,
    translations: {
      es: "Su receta está lista.",
      zh: "你的处方已经准备好了。",
      ar: "وصفتك الطبية جاهزة.",
      fr: "Votre ordonnance est prête.",
    },
  },
  {
    id: "md-013",
    english: "You need a refill on your prescription.",
    category: "Medications",
    critical: false,
    translations: {
      es: "Necesita una recarga de su receta.",
      zh: "你需要续配处方药。",
      ar: "تحتاج إلى تجديد وصفتك الطبية.",
      fr: "Vous devez renouveler votre ordonnance.",
    },
  },
  {
    id: "md-014",
    english: "Are you taking any herbal supplements?",
    category: "Medications",
    critical: false,
    translations: {
      es: "¿Está tomando algún suplemento herbal?",
      zh: "你在服用任何草药补充剂吗？",
      ar: "هل تتناول أي مكملات عشبية؟",
      fr: "Prenez-vous des compléments à base de plantes ?",
    },
    culturalNote: "Many cultures use traditional remedies that can interact with medications. Ask without judgment.",
  },
  {
    id: "md-015",
    english: "This medication may cause an upset stomach.",
    category: "Medications",
    critical: false,
    translations: {
      es: "Este medicamento puede causar malestar estomacal.",
      zh: "此药可能引起胃部不适。",
      ar: "قد يسبب هذا الدواء اضطراباً في المعدة.",
      fr: "Ce médicament peut causer des maux d'estomac.",
    },
  },
  {
    id: "md-016",
    english: "Stop taking this medication if you develop a rash.",
    category: "Medications",
    critical: true,
    translations: {
      es: "Deje de tomar este medicamento si le sale sarpullido.",
      zh: "如果出现皮疹，请停止服用此药。",
      ar: "توقف عن تناول هذا الدواء إذا ظهر طفح جلدي.",
      fr: "Arrêtez ce médicament si vous développez une éruption cutanée.",
    },
  },
  {
    id: "md-017",
    english: "Do you use an inhaler?",
    category: "Medications",
    critical: false,
    translations: {
      es: "¿Usa un inhalador?",
      zh: "你使用吸入器吗？",
      ar: "هل تستخدم جهاز استنشاق؟",
      fr: "Utilisez-vous un inhalateur ?",
    },
  },
  {
    id: "md-018",
    english: "Shake the bottle well before use.",
    category: "Medications",
    critical: false,
    translations: {
      es: "Agite bien el frasco antes de usar.",
      zh: "使用前请充分摇匀。",
      ar: "رُج الزجاجة جيداً قبل الاستخدام.",
      fr: "Agitez bien le flacon avant utilisation.",
    },
  },
  {
    id: "md-019",
    english: "This is an antibiotic.",
    category: "Medications",
    critical: false,
    translations: {
      es: "Este es un antibiótico.",
      zh: "这是抗生素。",
      ar: "هذا مضاد حيوي.",
      fr: "C'est un antibiotique.",
    },
  },
  {
    id: "md-020",
    english: "Take this with a full glass of water.",
    category: "Medications",
    critical: false,
    translations: {
      es: "Tómelo con un vaso lleno de agua.",
      zh: "请用一整杯水送服。",
      ar: "تناوله مع كوب كامل من الماء.",
      fr: "Prenez-le avec un grand verre d'eau.",
    },
  },
  {
    id: "md-021",
    english: "Do not stop taking this medication suddenly.",
    category: "Medications",
    critical: true,
    translations: {
      es: "No deje de tomar este medicamento de repente.",
      zh: "不要突然停用此药。",
      ar: "لا تتوقف عن تناول هذا الدواء فجأة.",
      fr: "N'arrêtez pas ce médicament brusquement.",
    },
  },
  {
    id: "md-022",
    english: "Keep all medications out of reach of children.",
    category: "Medications",
    critical: false,
    translations: {
      es: "Mantenga todos los medicamentos fuera del alcance de los niños.",
      zh: "请将所有药物放在儿童无法触及的地方。",
      ar: "احفظ جميع الأدوية بعيداً عن متناول الأطفال.",
      fr: "Gardez tous les médicaments hors de portée des enfants.",
    },
  },
  {
    id: "md-023",
    english: "This medication requires a prescription.",
    category: "Medications",
    critical: false,
    translations: {
      es: "Este medicamento requiere receta médica.",
      zh: "此药需要处方。",
      ar: "هذا الدواء يحتاج إلى وصفة طبية.",
      fr: "Ce médicament nécessite une ordonnance.",
    },
  },
  {
    id: "md-024",
    english: "You may experience side effects such as dizziness.",
    category: "Medications",
    critical: false,
    translations: {
      es: "Puede experimentar efectos secundarios como mareos.",
      zh: "你可能会出现头晕等副作用。",
      ar: "قد تعاني من آثار جانبية مثل الدوار.",
      fr: "Vous pouvez ressentir des effets secondaires tels que des vertiges.",
    },
  },
  {
    id: "md-025",
    english: "Have you missed any doses?",
    category: "Medications",
    critical: false,
    translations: {
      es: "¿Ha olvidado alguna dosis?",
      zh: "你有漏服过吗？",
      ar: "هل فاتتك أي جرعات؟",
      fr: "Avez-vous oublié des prises ?",
    },
  },

  // ============================================================
  // PROCEDURES (25+ phrases)
  // ============================================================
  {
    id: "pr-001",
    english: "We need to take an X-ray.",
    category: "Procedures",
    critical: false,
    translations: {
      es: "Necesitamos tomarle una radiografía.",
      zh: "我们需要给你拍X光。",
      ar: "نحتاج إلى أخذ صورة أشعة سينية.",
      fr: "Nous devons faire une radiographie.",
    },
  },
  {
    id: "pr-002",
    english: "You will need an MRI scan.",
    category: "Procedures",
    critical: false,
    translations: {
      es: "Necesitará una resonancia magnética.",
      zh: "你需要做一个核磁共振检查。",
      ar: "ستحتاج إلى تصوير بالرنين المغناطيسي.",
      fr: "Vous aurez besoin d'une IRM.",
    },
  },
  {
    id: "pr-003",
    english: "We are going to give you local anesthesia.",
    category: "Procedures",
    critical: true,
    translations: {
      es: "Vamos a darle anestesia local.",
      zh: "我们要给你局部麻醉。",
      ar: "سنعطيك تخديراً موضعياً.",
      fr: "Nous allons vous administrer une anesthésie locale.",
    },
  },
  {
    id: "pr-004",
    english: "You will need to fast for 12 hours before the procedure.",
    category: "Procedures",
    critical: true,
    translations: {
      es: "Deberá ayunar durante 12 horas antes del procedimiento.",
      zh: "手术前你需要禁食12小时。",
      ar: "ستحتاج إلى الصيام لمدة 12 ساعة قبل الإجراء.",
      fr: "Vous devrez être à jeun pendant 12 heures avant l'intervention.",
    },
    culturalNote: "During Ramadan, Muslim patients may already be fasting. Be sensitive to the overlap.",
  },
  {
    id: "pr-005",
    english: "I am going to listen to your heart and lungs.",
    category: "Procedures",
    critical: false,
    translations: {
      es: "Voy a escuchar su corazón y pulmones.",
      zh: "我要听一下你的心脏和肺。",
      ar: "سأستمع إلى قلبك ورئتيك.",
      fr: "Je vais écouter votre cœur et vos poumons.",
    },
  },
  {
    id: "pr-006",
    english: "I need to draw some blood.",
    category: "Procedures",
    critical: false,
    translations: {
      es: "Necesito sacarle algo de sangre.",
      zh: "我需要抽一些血。",
      ar: "أحتاج إلى سحب بعض الدم.",
      fr: "Je dois faire une prise de sang.",
    },
  },
  {
    id: "pr-007",
    english: "You will feel a small pinch.",
    category: "Procedures",
    critical: false,
    translations: {
      es: "Sentirá un pequeño pinchazo.",
      zh: "你会感到轻微的刺痛。",
      ar: "ستشعر بوخزة صغيرة.",
      fr: "Vous allez sentir une petite piqûre.",
    },
  },
  {
    id: "pr-008",
    english: "Please remove your jewelry before the procedure.",
    category: "Procedures",
    critical: false,
    translations: {
      es: "Por favor, quítese las joyas antes del procedimiento.",
      zh: "手术前请取下您的首饰。",
      ar: "يرجى إزالة المجوهرات قبل الإجراء.",
      fr: "Veuillez retirer vos bijoux avant l'intervention.",
    },
    culturalNote: "Some religious items (crosses, hijab pins, sacred threads) have deep significance. Ask respectfully and offer alternatives.",
  },
  {
    id: "pr-009",
    english: "The procedure will take about 30 minutes.",
    category: "Procedures",
    critical: false,
    translations: {
      es: "El procedimiento tomará aproximadamente 30 minutos.",
      zh: "手术大约需要30分钟。",
      ar: "سيستغرق الإجراء حوالي 30 دقيقة.",
      fr: "L'intervention durera environ 30 minutes.",
    },
  },
  {
    id: "pr-010",
    english: "We need to insert a catheter.",
    category: "Procedures",
    critical: false,
    translations: {
      es: "Necesitamos insertar un catéter.",
      zh: "我们需要插入导管。",
      ar: "نحتاج إلى إدخال قسطرة.",
      fr: "Nous devons poser un cathéter.",
    },
  },
  {
    id: "pr-011",
    english: "Please change into this hospital gown.",
    category: "Procedures",
    critical: false,
    translations: {
      es: "Por favor, cámbiese y póngase esta bata de hospital.",
      zh: "请换上这件病号服。",
      ar: "يرجى تغيير ملابسك وارتداء ثوب المستشفى.",
      fr: "Veuillez enfiler cette blouse d'hôpital.",
    },
    culturalNote: "Some patients may need same-gender staff for disrobing due to religious or cultural requirements.",
  },
  {
    id: "pr-012",
    english: "We need to put you under general anesthesia.",
    category: "Procedures",
    critical: true,
    translations: {
      es: "Necesitamos ponerle anestesia general.",
      zh: "我们需要给你全身麻醉。",
      ar: "نحتاج إلى إعطائك تخديراً عاماً.",
      fr: "Nous devons vous mettre sous anesthésie générale.",
    },
  },
  {
    id: "pr-013",
    english: "I am going to check your blood pressure.",
    category: "Procedures",
    critical: false,
    translations: {
      es: "Voy a tomarle la presión arterial.",
      zh: "我要量一下你的血压。",
      ar: "سأقيس ضغط دمك.",
      fr: "Je vais vérifier votre tension artérielle.",
    },
  },
  {
    id: "pr-014",
    english: "We need a urine sample.",
    category: "Procedures",
    critical: false,
    translations: {
      es: "Necesitamos una muestra de orina.",
      zh: "我们需要一个尿液样本。",
      ar: "نحتاج إلى عينة بول.",
      fr: "Nous avons besoin d'un échantillon d'urine.",
    },
  },
  {
    id: "pr-015",
    english: "The stitches will dissolve on their own.",
    category: "Procedures",
    critical: false,
    translations: {
      es: "Los puntos se disolverán por sí solos.",
      zh: "缝线会自行溶解。",
      ar: "ستذوب الغرز من تلقاء نفسها.",
      fr: "Les points de suture se résorberont d'eux-mêmes.",
    },
  },
  {
    id: "pr-016",
    english: "You will need physical therapy after recovery.",
    category: "Procedures",
    critical: false,
    translations: {
      es: "Necesitará fisioterapia después de la recuperación.",
      zh: "康复后你需要进行物理治疗。",
      ar: "ستحتاج إلى علاج طبيعي بعد التعافي.",
      fr: "Vous aurez besoin de kinésithérapie après la guérison.",
    },
  },
  {
    id: "pr-017",
    english: "I am going to examine your eyes.",
    category: "Procedures",
    critical: false,
    translations: {
      es: "Voy a examinarle los ojos.",
      zh: "我要检查一下你的眼睛。",
      ar: "سأفحص عينيك.",
      fr: "Je vais examiner vos yeux.",
    },
  },
  {
    id: "pr-018",
    english: "You need a CT scan.",
    category: "Procedures",
    critical: false,
    translations: {
      es: "Necesita una tomografía computarizada.",
      zh: "你需要做CT扫描。",
      ar: "تحتاج إلى تصوير مقطعي محوسب.",
      fr: "Vous avez besoin d'un scanner.",
    },
  },
  {
    id: "pr-019",
    english: "We will monitor you overnight.",
    category: "Procedures",
    critical: false,
    translations: {
      es: "Lo/la monitorizaremos durante la noche.",
      zh: "我们会对你进行过夜观察。",
      ar: "سنراقبك طوال الليل.",
      fr: "Nous allons vous surveiller pendant la nuit.",
    },
  },
  {
    id: "pr-020",
    english: "The biopsy results will be available in a few days.",
    category: "Procedures",
    critical: false,
    translations: {
      es: "Los resultados de la biopsia estarán disponibles en unos días.",
      zh: "活检结果几天后出来。",
      ar: "ستكون نتائج الخزعة متاحة خلال أيام قليلة.",
      fr: "Les résultats de la biopsie seront disponibles dans quelques jours.",
    },
  },
  {
    id: "pr-021",
    english: "Please take a deep breath and hold it.",
    category: "Procedures",
    critical: false,
    translations: {
      es: "Por favor, respire profundamente y contenga la respiración.",
      zh: "请深呼吸并屏住。",
      ar: "من فضلك خذ نفساً عميقاً واحبسه.",
      fr: "Veuillez prendre une grande inspiration et la retenir.",
    },
  },
  {
    id: "pr-022",
    english: "I am going to numb the area first.",
    category: "Procedures",
    critical: false,
    translations: {
      es: "Primero voy a adormecer la zona.",
      zh: "我先要麻醉这个区域。",
      ar: "سأقوم بتخدير المنطقة أولاً.",
      fr: "Je vais d'abord anesthésier la zone.",
    },
  },
  {
    id: "pr-023",
    english: "You will need to wear a cast for six weeks.",
    category: "Procedures",
    critical: false,
    translations: {
      es: "Necesitará usar un yeso durante seis semanas.",
      zh: "你需要戴石膏六周。",
      ar: "ستحتاج إلى ارتداء جبيرة لمدة ستة أسابيع.",
      fr: "Vous devrez porter un plâtre pendant six semaines.",
    },
  },
  {
    id: "pr-024",
    english: "We are scheduling you for surgery.",
    category: "Procedures",
    critical: false,
    translations: {
      es: "Le estamos programando para cirugía.",
      zh: "我们正在为你安排手术。",
      ar: "نحن نحدد لك موعداً لعملية جراحية.",
      fr: "Nous vous programmons pour une opération.",
    },
  },
  {
    id: "pr-025",
    english: "You can go home today.",
    category: "Procedures",
    critical: false,
    translations: {
      es: "Puede irse a casa hoy.",
      zh: "你今天可以回家了。",
      ar: "يمكنك العودة إلى المنزل اليوم.",
      fr: "Vous pouvez rentrer chez vous aujourd'hui.",
    },
  },

  // ============================================================
  // CONSENT (25+ phrases)
  // ============================================================
  {
    id: "cn-001",
    english: "Do you understand the risks of this procedure?",
    category: "Consent",
    critical: true,
    translations: {
      es: "¿Entiende los riesgos de este procedimiento?",
      zh: "你了解这个手术的风险吗？",
      ar: "هل تفهم مخاطر هذا الإجراء؟",
      fr: "Comprenez-vous les risques de cette intervention ?",
    },
  },
  {
    id: "cn-002",
    english: "You have the right to refuse treatment.",
    category: "Consent",
    critical: true,
    translations: {
      es: "Tiene derecho a rechazar el tratamiento.",
      zh: "你有权拒绝治疗。",
      ar: "لديك الحق في رفض العلاج.",
      fr: "Vous avez le droit de refuser le traitement.",
    },
  },
  {
    id: "cn-003",
    english: "Please sign this consent form.",
    category: "Consent",
    critical: true,
    translations: {
      es: "Por favor, firme este formulario de consentimiento.",
      zh: "请签署这份知情同意书。",
      ar: "يرجى التوقيع على نموذج الموافقة هذا.",
      fr: "Veuillez signer ce formulaire de consentement.",
    },
  },
  {
    id: "cn-004",
    english: "Do you have any questions before we proceed?",
    category: "Consent",
    critical: true,
    translations: {
      es: "¿Tiene alguna pregunta antes de proceder?",
      zh: "在我们继续之前你有什么问题吗？",
      ar: "هل لديك أي أسئلة قبل أن نبدأ؟",
      fr: "Avez-vous des questions avant que nous commencions ?",
    },
  },
  {
    id: "cn-005",
    english: "We need your written permission for this surgery.",
    category: "Consent",
    critical: true,
    translations: {
      es: "Necesitamos su permiso por escrito para esta cirugía.",
      zh: "我们需要你对这次手术的书面同意。",
      ar: "نحتاج إلى إذنك الكتابي لهذه الجراحة.",
      fr: "Nous avons besoin de votre autorisation écrite pour cette opération.",
    },
  },
  {
    id: "cn-006",
    english: "The alternative treatments are...",
    category: "Consent",
    critical: true,
    translations: {
      es: "Los tratamientos alternativos son...",
      zh: "替代治疗方案有...",
      ar: "العلاجات البديلة هي...",
      fr: "Les traitements alternatifs sont...",
    },
  },
  {
    id: "cn-007",
    english: "Would you like a family member present?",
    category: "Consent",
    critical: false,
    translations: {
      es: "¿Le gustaría que un familiar esté presente?",
      zh: "你希望有家人在场吗？",
      ar: "هل تريد أن يكون أحد أفراد عائلتك حاضراً؟",
      fr: "Souhaitez-vous qu'un membre de votre famille soit présent ?",
    },
  },
  {
    id: "cn-008",
    english: "Do you have a healthcare proxy or power of attorney?",
    category: "Consent",
    critical: true,
    translations: {
      es: "¿Tiene un representante de atención médica o poder notarial?",
      zh: "你有医疗代理人或授权委托书吗？",
      ar: "هل لديك وكيل رعاية صحية أو توكيل؟",
      fr: "Avez-vous une personne de confiance ou une procuration ?",
    },
  },
  {
    id: "cn-009",
    english: "The success rate for this procedure is approximately...",
    category: "Consent",
    critical: true,
    translations: {
      es: "La tasa de éxito de este procedimiento es aproximadamente...",
      zh: "这个手术的成功率大约是...",
      ar: "معدل نجاح هذا الإجراء تقريباً...",
      fr: "Le taux de réussite de cette intervention est d'environ...",
    },
  },
  {
    id: "cn-010",
    english: "You can withdraw your consent at any time.",
    category: "Consent",
    critical: true,
    translations: {
      es: "Puede retirar su consentimiento en cualquier momento.",
      zh: "你可以随时撤回你的同意。",
      ar: "يمكنك سحب موافقتك في أي وقت.",
      fr: "Vous pouvez retirer votre consentement à tout moment.",
    },
  },
  {
    id: "cn-011",
    english: "Would you like an interpreter present?",
    category: "Consent",
    critical: true,
    translations: {
      es: "¿Le gustaría que haya un intérprete presente?",
      zh: "你需要一位翻译在场吗？",
      ar: "هل تريد مترجماً حاضراً؟",
      fr: "Souhaitez-vous la présence d'un interprète ?",
    },
    culturalNote: "Legally required in many jurisdictions for informed consent. Never use children as medical interpreters.",
  },
  {
    id: "cn-012",
    english: "This form explains the procedure in detail.",
    category: "Consent",
    critical: false,
    translations: {
      es: "Este formulario explica el procedimiento en detalle.",
      zh: "这份表格详细说明了手术过程。",
      ar: "هذا النموذج يشرح الإجراء بالتفصيل.",
      fr: "Ce formulaire explique l'intervention en détail.",
    },
  },
  {
    id: "cn-013",
    english: "Do you understand everything I have explained?",
    category: "Consent",
    critical: true,
    translations: {
      es: "¿Entiende todo lo que le he explicado?",
      zh: "你理解我解释的所有内容吗？",
      ar: "هل تفهم كل ما شرحته؟",
      fr: "Comprenez-vous tout ce que je vous ai expliqué ?",
    },
  },
  {
    id: "cn-014",
    english: "We respect your religious and cultural beliefs.",
    category: "Consent",
    critical: false,
    translations: {
      es: "Respetamos sus creencias religiosas y culturales.",
      zh: "我们尊重你的宗教和文化信仰。",
      ar: "نحترم معتقداتك الدينية والثقافية.",
      fr: "Nous respectons vos croyances religieuses et culturelles.",
    },
  },
  {
    id: "cn-015",
    english: "Do you have an advance directive or living will?",
    category: "Consent",
    critical: true,
    translations: {
      es: "¿Tiene una directiva anticipada o testamento vital?",
      zh: "你有预先指示或生前遗嘱吗？",
      ar: "هل لديك توجيهات مسبقة أو وصية حية؟",
      fr: "Avez-vous des directives anticipées ou un testament de vie ?",
    },
  },
  {
    id: "cn-016",
    english: "The possible complications include...",
    category: "Consent",
    critical: true,
    translations: {
      es: "Las posibles complicaciones incluyen...",
      zh: "可能的并发症包括...",
      ar: "المضاعفات المحتملة تشمل...",
      fr: "Les complications possibles comprennent...",
    },
  },
  {
    id: "cn-017",
    english: "Your information is kept confidential.",
    category: "Consent",
    critical: false,
    translations: {
      es: "Su información se mantiene confidencial.",
      zh: "你的信息将保密处理。",
      ar: "معلوماتك تبقى سرية.",
      fr: "Vos informations sont confidentielles.",
    },
  },
  {
    id: "cn-018",
    english: "Do you consent to blood transfusion if needed?",
    category: "Consent",
    critical: true,
    translations: {
      es: "¿Consiente recibir una transfusión de sangre si es necesario?",
      zh: "如果需要，你同意输血吗？",
      ar: "هل توافق على نقل الدم إذا لزم الأمر؟",
      fr: "Consentez-vous à une transfusion sanguine si nécessaire ?",
    },
    culturalNote: "Jehovah's Witnesses and some other groups refuse blood transfusions. This must be documented and respected.",
  },
  {
    id: "cn-019",
    english: "Recovery time is expected to be...",
    category: "Consent",
    critical: false,
    translations: {
      es: "Se espera que el tiempo de recuperación sea...",
      zh: "预计恢复时间为...",
      ar: "من المتوقع أن تكون فترة التعافي...",
      fr: "Le temps de récupération prévu est de...",
    },
  },
  {
    id: "cn-020",
    english: "Who is your emergency contact?",
    category: "Consent",
    critical: true,
    translations: {
      es: "¿Quién es su contacto de emergencia?",
      zh: "你的紧急联系人是谁？",
      ar: "من هو جهة اتصالك في حالات الطوارئ؟",
      fr: "Qui est votre contact d'urgence ?",
    },
  },
  {
    id: "cn-021",
    english: "This procedure is medically necessary.",
    category: "Consent",
    critical: false,
    translations: {
      es: "Este procedimiento es médicamente necesario.",
      zh: "这个手术在医学上是必要的。",
      ar: "هذا الإجراء ضروري طبياً.",
      fr: "Cette intervention est médicalement nécessaire.",
    },
  },
  {
    id: "cn-022",
    english: "Would you like a second opinion?",
    category: "Consent",
    critical: false,
    translations: {
      es: "¿Le gustaría obtener una segunda opinión?",
      zh: "你想要再咨询一下其他医生吗？",
      ar: "هل تريد الحصول على رأي طبي آخر؟",
      fr: "Souhaitez-vous un deuxième avis ?",
    },
  },
  {
    id: "cn-023",
    english: "We will do everything we can to minimize your discomfort.",
    category: "Consent",
    critical: false,
    translations: {
      es: "Haremos todo lo posible para minimizar su molestia.",
      zh: "我们会尽一切努力减少你的不适。",
      ar: "سنبذل كل ما بوسعنا لتقليل إزعاجك.",
      fr: "Nous ferons tout notre possible pour minimiser votre inconfort.",
    },
  },
  {
    id: "cn-024",
    english: "Is there anything that prevents you from giving consent?",
    category: "Consent",
    critical: true,
    translations: {
      es: "¿Hay algo que le impida dar su consentimiento?",
      zh: "有什么原因使你无法给予同意吗？",
      ar: "هل هناك ما يمنعك من إعطاء الموافقة؟",
      fr: "Y a-t-il quelque chose qui vous empêche de donner votre consentement ?",
    },
  },
  {
    id: "cn-025",
    english: "The doctor performing the procedure is Dr...",
    category: "Consent",
    critical: false,
    translations: {
      es: "El médico que realizará el procedimiento es el Dr...",
      zh: "执行手术的医生是...医生。",
      ar: "الطبيب الذي سيجري العملية هو الدكتور...",
      fr: "Le médecin qui effectuera l'intervention est le Dr...",
    },
  },

  // ============================================================
  // MENTAL HEALTH (25+ phrases)
  // ============================================================
  {
    id: "mh-001",
    english: "Are you having thoughts of harming yourself?",
    category: "Mental Health",
    critical: true,
    translations: {
      es: "¿Tiene pensamientos de hacerse daño?",
      zh: "你有伤害自己的想法吗？",
      ar: "هل لديك أفكار بإيذاء نفسك؟",
      fr: "Avez-vous des pensées d'automutilation ?",
    },
    culturalNote: "Ask directly and without judgment. In many cultures, mental health carries significant stigma.",
  },
  {
    id: "mh-002",
    english: "How have you been feeling emotionally?",
    category: "Mental Health",
    critical: false,
    translations: {
      es: "¿Cómo se ha sentido emocionalmente?",
      zh: "你最近的情绪怎么样？",
      ar: "كيف حالك العاطفية؟",
      fr: "Comment vous sentez-vous émotionnellement ?",
    },
  },
  {
    id: "mh-003",
    english: "Have you been feeling anxious or worried?",
    category: "Mental Health",
    critical: false,
    translations: {
      es: "¿Se ha sentido ansioso/a o preocupado/a?",
      zh: "你是否感到焦虑或担忧？",
      ar: "هل تشعر بالقلق أو التوتر؟",
      fr: "Vous êtes-vous senti(e) anxieux/anxieuse ou inquiet/inquiète ?",
    },
  },
  {
    id: "mh-004",
    english: "Are you sleeping well?",
    category: "Mental Health",
    critical: false,
    translations: {
      es: "¿Está durmiendo bien?",
      zh: "你睡得好吗？",
      ar: "هل تنام جيداً؟",
      fr: "Dormez-vous bien ?",
    },
  },
  {
    id: "mh-005",
    english: "Have you lost interest in things you used to enjoy?",
    category: "Mental Health",
    critical: true,
    translations: {
      es: "¿Ha perdido interés en cosas que antes disfrutaba?",
      zh: "你是否对以前喜欢的事情失去了兴趣？",
      ar: "هل فقدت اهتمامك بالأشياء التي كنت تستمتع بها؟",
      fr: "Avez-vous perdu l'intérêt pour les choses que vous aimiez ?",
    },
  },
  {
    id: "mh-006",
    english: "You are not alone. We are here to help.",
    category: "Mental Health",
    critical: false,
    translations: {
      es: "No está solo/a. Estamos aquí para ayudarle.",
      zh: "你不是一个人。我们在这里帮助你。",
      ar: "أنت لست وحدك. نحن هنا لمساعدتك.",
      fr: "Vous n'êtes pas seul(e). Nous sommes là pour vous aider.",
    },
  },
  {
    id: "mh-007",
    english: "Have you experienced a traumatic event recently?",
    category: "Mental Health",
    critical: true,
    translations: {
      es: "¿Ha experimentado un evento traumático recientemente?",
      zh: "你最近经历过创伤事件吗？",
      ar: "هل تعرضت لحدث صادم مؤخراً؟",
      fr: "Avez-vous vécu un événement traumatisant récemment ?",
    },
  },
  {
    id: "mh-008",
    english: "Would you like to speak with a counselor?",
    category: "Mental Health",
    critical: false,
    translations: {
      es: "¿Le gustaría hablar con un consejero?",
      zh: "你想和心理咨询师谈谈吗？",
      ar: "هل تريد التحدث مع مستشار؟",
      fr: "Souhaitez-vous parler à un conseiller ?",
    },
  },
  {
    id: "mh-009",
    english: "Do you feel safe at home?",
    category: "Mental Health",
    critical: true,
    translations: {
      es: "¿Se siente seguro/a en casa?",
      zh: "你在家里感到安全吗？",
      ar: "هل تشعر بالأمان في المنزل؟",
      fr: "Vous sentez-vous en sécurité chez vous ?",
    },
  },
  {
    id: "mh-010",
    english: "Have you been having trouble concentrating?",
    category: "Mental Health",
    critical: false,
    translations: {
      es: "¿Ha tenido problemas para concentrarse?",
      zh: "你是否难以集中注意力？",
      ar: "هل تواجه صعوبة في التركيز؟",
      fr: "Avez-vous du mal à vous concentrer ?",
    },
  },
  {
    id: "mh-011",
    english: "Are you using any substances to cope?",
    category: "Mental Health",
    critical: true,
    translations: {
      es: "¿Está usando alguna sustancia para lidiar con la situación?",
      zh: "你是否在使用某些物质来应对？",
      ar: "هل تستخدم أي مواد للتأقلم؟",
      fr: "Utilisez-vous des substances pour faire face ?",
    },
  },
  {
    id: "mh-012",
    english: "How long have you been feeling this way?",
    category: "Mental Health",
    critical: false,
    translations: {
      es: "¿Cuánto tiempo lleva sintiéndose así?",
      zh: "你有这种感觉多久了？",
      ar: "منذ متى وأنت تشعر بهذه الطريقة؟",
      fr: "Depuis combien de temps vous sentez-vous ainsi ?",
    },
  },
  {
    id: "mh-013",
    english: "Do you have a support system — friends or family?",
    category: "Mental Health",
    critical: false,
    translations: {
      es: "¿Tiene un sistema de apoyo — amigos o familiares?",
      zh: "你有支持系统吗——朋友或家人？",
      ar: "هل لديك نظام دعم — أصدقاء أو عائلة؟",
      fr: "Avez-vous un réseau de soutien — amis ou famille ?",
    },
  },
  {
    id: "mh-014",
    english: "Everything you share with me is confidential.",
    category: "Mental Health",
    critical: false,
    translations: {
      es: "Todo lo que comparta conmigo es confidencial.",
      zh: "你告诉我的一切都是保密的。",
      ar: "كل ما تشاركه معي سري.",
      fr: "Tout ce que vous me confiez est confidentiel.",
    },
  },
  {
    id: "mh-015",
    english: "Have you had thoughts of suicide?",
    category: "Mental Health",
    critical: true,
    translations: {
      es: "¿Ha tenido pensamientos suicidas?",
      zh: "你有过自杀的想法吗？",
      ar: "هل راودتك أفكار انتحارية؟",
      fr: "Avez-vous eu des pensées suicidaires ?",
    },
    culturalNote: "Ask directly. Research shows asking about suicide does not increase risk — it opens the door to help.",
  },
  {
    id: "mh-016",
    english: "Would you like me to explain how therapy works?",
    category: "Mental Health",
    critical: false,
    translations: {
      es: "¿Le gustaría que le explique cómo funciona la terapia?",
      zh: "你想让我解释一下治疗是怎么进行的吗？",
      ar: "هل تريد أن أشرح لك كيف يعمل العلاج؟",
      fr: "Souhaitez-vous que je vous explique comment fonctionne la thérapie ?",
    },
  },
  {
    id: "mh-017",
    english: "It takes courage to ask for help.",
    category: "Mental Health",
    critical: false,
    translations: {
      es: "Se necesita valor para pedir ayuda.",
      zh: "寻求帮助需要勇气。",
      ar: "يتطلب الأمر شجاعة لطلب المساعدة.",
      fr: "Il faut du courage pour demander de l'aide.",
    },
  },
  {
    id: "mh-018",
    english: "Are you hearing voices or seeing things others cannot?",
    category: "Mental Health",
    critical: true,
    translations: {
      es: "¿Está escuchando voces o viendo cosas que otros no pueden?",
      zh: "你是否听到别人听不到的声音或看到别人看不到的东西？",
      ar: "هل تسمع أصواتاً أو ترى أشياء لا يراها الآخرون؟",
      fr: "Entendez-vous des voix ou voyez-vous des choses que les autres ne voient pas ?",
    },
  },
  {
    id: "mh-019",
    english: "Do you have a plan to harm yourself?",
    category: "Mental Health",
    critical: true,
    translations: {
      es: "¿Tiene un plan para hacerse daño?",
      zh: "你有伤害自己的计划吗？",
      ar: "هل لديك خطة لإيذاء نفسك؟",
      fr: "Avez-vous un plan pour vous faire du mal ?",
    },
  },
  {
    id: "mh-020",
    english: "Have you experienced panic attacks?",
    category: "Mental Health",
    critical: false,
    translations: {
      es: "¿Ha experimentado ataques de pánico?",
      zh: "你有过恐慌发作吗？",
      ar: "هل عانيت من نوبات ذعر؟",
      fr: "Avez-vous eu des crises de panique ?",
    },
  },
  {
    id: "mh-021",
    english: "Your feelings are valid.",
    category: "Mental Health",
    critical: false,
    translations: {
      es: "Sus sentimientos son válidos.",
      zh: "你的感受是正当的。",
      ar: "مشاعرك مشروعة.",
      fr: "Vos sentiments sont légitimes.",
    },
  },
  {
    id: "mh-022",
    english: "Have you been eating regularly?",
    category: "Mental Health",
    critical: false,
    translations: {
      es: "¿Ha estado comiendo regularmente?",
      zh: "你有规律地吃饭吗？",
      ar: "هل تأكل بانتظام؟",
      fr: "Mangez-vous régulièrement ?",
    },
  },
  {
    id: "mh-023",
    english: "Do you feel hopeless about the future?",
    category: "Mental Health",
    critical: true,
    translations: {
      es: "¿Se siente desesperanzado/a sobre el futuro?",
      zh: "你对未来感到绝望吗？",
      ar: "هل تشعر باليأس تجاه المستقبل؟",
      fr: "Vous sentez-vous désespéré(e) quant à l'avenir ?",
    },
  },
  {
    id: "mh-024",
    english: "We can work through this together.",
    category: "Mental Health",
    critical: false,
    translations: {
      es: "Podemos superar esto juntos.",
      zh: "我们可以一起度过这一切。",
      ar: "يمكننا تجاوز هذا معاً.",
      fr: "Nous pouvons traverser cela ensemble.",
    },
  },
  {
    id: "mh-025",
    english: "Have you ever been diagnosed with a mental health condition?",
    category: "Mental Health",
    critical: false,
    translations: {
      es: "¿Alguna vez le han diagnosticado una condición de salud mental?",
      zh: "你曾被诊断出有心理健康问题吗？",
      ar: "هل تم تشخيصك بحالة نفسية من قبل؟",
      fr: "Avez-vous déjà été diagnostiqué(e) avec un trouble mental ?",
    },
  },

  // ============================================================
  // PEDIATRIC (25+ phrases)
  // ============================================================
  {
    id: "pd-001",
    english: "How old is your child?",
    category: "Pediatric",
    critical: false,
    translations: {
      es: "¿Cuántos años tiene su hijo/a?",
      zh: "你的孩子多大了？",
      ar: "كم عمر طفلك؟",
      fr: "Quel âge a votre enfant ?",
    },
  },
  {
    id: "pd-002",
    english: "Is your child up to date on vaccinations?",
    category: "Pediatric",
    critical: true,
    translations: {
      es: "¿Tiene su hijo/a las vacunas al día?",
      zh: "你的孩子疫苗接种是否都更新了？",
      ar: "هل طفلك محدّث بالتطعيمات؟",
      fr: "Votre enfant est-il à jour dans ses vaccinations ?",
    },
    culturalNote: "Vaccine hesitancy varies across cultures. Approach with information, not judgment.",
  },
  {
    id: "pd-003",
    english: "Has your child had a fever?",
    category: "Pediatric",
    critical: false,
    translations: {
      es: "¿Ha tenido fiebre su hijo/a?",
      zh: "你的孩子发烧了吗？",
      ar: "هل عانى طفلك من حمى؟",
      fr: "Votre enfant a-t-il eu de la fièvre ?",
    },
  },
  {
    id: "pd-004",
    english: "Is your child eating and drinking normally?",
    category: "Pediatric",
    critical: true,
    translations: {
      es: "¿Su hijo/a está comiendo y bebiendo normalmente?",
      zh: "你的孩子吃喝正常吗？",
      ar: "هل يأكل ويشرب طفلك بشكل طبيعي؟",
      fr: "Votre enfant mange-t-il et boit-il normalement ?",
    },
  },
  {
    id: "pd-005",
    english: "When was the last wet diaper?",
    category: "Pediatric",
    critical: true,
    translations: {
      es: "¿Cuándo fue el último pañal mojado?",
      zh: "最后一次湿尿布是什么时候？",
      ar: "متى كان آخر حفاض مبلل؟",
      fr: "Quand est-ce que la dernière couche était mouillée ?",
    },
  },
  {
    id: "pd-006",
    english: "Is your child allergic to anything?",
    category: "Pediatric",
    critical: true,
    translations: {
      es: "¿Su hijo/a es alérgico/a a algo?",
      zh: "你的孩子对什么东西过敏吗？",
      ar: "هل يعاني طفلك من حساسية تجاه أي شيء؟",
      fr: "Votre enfant est-il allergique à quelque chose ?",
    },
  },
  {
    id: "pd-007",
    english: "How much does your child weigh?",
    category: "Pediatric",
    critical: true,
    translations: {
      es: "¿Cuánto pesa su hijo/a?",
      zh: "你的孩子体重多少？",
      ar: "كم وزن طفلك؟",
      fr: "Combien pèse votre enfant ?",
    },
    culturalNote: "Weight is critical for pediatric medication dosing. Always verify.",
  },
  {
    id: "pd-008",
    english: "Has your child been around anyone who is sick?",
    category: "Pediatric",
    critical: false,
    translations: {
      es: "¿Su hijo/a ha estado cerca de alguien que esté enfermo?",
      zh: "你的孩子接触过生病的人吗？",
      ar: "هل كان طفلك بالقرب من شخص مريض؟",
      fr: "Votre enfant a-t-il été en contact avec une personne malade ?",
    },
  },
  {
    id: "pd-009",
    english: "We need to keep your child hydrated.",
    category: "Pediatric",
    critical: true,
    translations: {
      es: "Necesitamos mantener a su hijo/a hidratado/a.",
      zh: "我们需要保持你的孩子充足的水分。",
      ar: "نحتاج إلى إبقاء طفلك رطباً.",
      fr: "Nous devons garder votre enfant hydraté(e).",
    },
  },
  {
    id: "pd-010",
    english: "Your child needs to rest.",
    category: "Pediatric",
    critical: false,
    translations: {
      es: "Su hijo/a necesita descansar.",
      zh: "你的孩子需要休息。",
      ar: "طفلك بحاجة إلى الراحة.",
      fr: "Votre enfant a besoin de repos.",
    },
  },
  {
    id: "pd-011",
    english: "Was your child born full-term?",
    category: "Pediatric",
    critical: false,
    translations: {
      es: "¿Su hijo/a nació a término?",
      zh: "你的孩子是足月出生的吗？",
      ar: "هل ولد طفلك في موعده الطبيعي؟",
      fr: "Votre enfant est-il né à terme ?",
    },
  },
  {
    id: "pd-012",
    english: "Were there any complications during birth?",
    category: "Pediatric",
    critical: false,
    translations: {
      es: "¿Hubo alguna complicación durante el parto?",
      zh: "分娩过程中有什么并发症吗？",
      ar: "هل كانت هناك أي مضاعفات أثناء الولادة؟",
      fr: "Y a-t-il eu des complications lors de l'accouchement ?",
    },
  },
  {
    id: "pd-013",
    english: "Is your child reaching developmental milestones?",
    category: "Pediatric",
    critical: false,
    translations: {
      es: "¿Su hijo/a está alcanzando los hitos del desarrollo?",
      zh: "你的孩子达到了发育里程碑吗？",
      ar: "هل يحقق طفلك مراحل النمو المتوقعة؟",
      fr: "Votre enfant atteint-il les étapes de développement ?",
    },
  },
  {
    id: "pd-014",
    english: "Your child has an ear infection.",
    category: "Pediatric",
    critical: false,
    translations: {
      es: "Su hijo/a tiene una infección de oído.",
      zh: "你的孩子耳朵感染了。",
      ar: "طفلك يعاني من التهاب في الأذن.",
      fr: "Votre enfant a une otite.",
    },
  },
  {
    id: "pd-015",
    english: "This is a safe environment for your child.",
    category: "Pediatric",
    critical: false,
    translations: {
      es: "Este es un ambiente seguro para su hijo/a.",
      zh: "这里对你的孩子是安全的环境。",
      ar: "هذه بيئة آمنة لطفلك.",
      fr: "C'est un environnement sûr pour votre enfant.",
    },
  },
  {
    id: "pd-016",
    english: "Are you breastfeeding or formula feeding?",
    category: "Pediatric",
    critical: false,
    translations: {
      es: "¿Está dando pecho o fórmula?",
      zh: "你是母乳喂养还是配方奶粉喂养？",
      ar: "هل ترضعين طبيعياً أم صناعياً؟",
      fr: "Allaitez-vous ou donnez-vous le biberon ?",
    },
  },
  {
    id: "pd-017",
    english: "Has your child had any rashes or skin changes?",
    category: "Pediatric",
    critical: false,
    translations: {
      es: "¿Su hijo/a ha tenido sarpullidos o cambios en la piel?",
      zh: "你的孩子有皮疹或皮肤变化吗？",
      ar: "هل عانى طفلك من أي طفح جلدي أو تغيرات جلدية؟",
      fr: "Votre enfant a-t-il eu des éruptions cutanées ou des changements de peau ?",
    },
  },
  {
    id: "pd-018",
    english: "We would like to run some tests on your child.",
    category: "Pediatric",
    critical: false,
    translations: {
      es: "Nos gustaría hacerle algunas pruebas a su hijo/a.",
      zh: "我们想给你的孩子做一些检查。",
      ar: "نود إجراء بعض الفحوصات لطفلك.",
      fr: "Nous aimerions faire des examens à votre enfant.",
    },
  },
  {
    id: "pd-019",
    english: "Your child's temperature is elevated.",
    category: "Pediatric",
    critical: false,
    translations: {
      es: "La temperatura de su hijo/a está elevada.",
      zh: "你孩子的体温偏高。",
      ar: "درجة حرارة طفلك مرتفعة.",
      fr: "La température de votre enfant est élevée.",
    },
  },
  {
    id: "pd-020",
    english: "Give children's dose only — do not give adult medication.",
    category: "Pediatric",
    critical: true,
    translations: {
      es: "Dé solo la dosis pediátrica — no dé medicamento para adultos.",
      zh: "只给儿童剂量——不要给成人药物。",
      ar: "أعطِ جرعة الأطفال فقط — لا تعطِ دواء البالغين.",
      fr: "Donnez uniquement la dose enfant — ne donnez pas de médicament adulte.",
    },
  },
  {
    id: "pd-021",
    english: "How many hours of sleep is your child getting?",
    category: "Pediatric",
    critical: false,
    translations: {
      es: "¿Cuántas horas duerme su hijo/a?",
      zh: "你的孩子睡几个小时？",
      ar: "كم ساعة ينام طفلك؟",
      fr: "Combien d'heures votre enfant dort-il ?",
    },
  },
  {
    id: "pd-022",
    english: "Has your child been more irritable than usual?",
    category: "Pediatric",
    critical: false,
    translations: {
      es: "¿Su hijo/a ha estado más irritable de lo habitual?",
      zh: "你的孩子比平时更烦躁吗？",
      ar: "هل كان طفلك أكثر انزعاجاً من المعتاد؟",
      fr: "Votre enfant a-t-il été plus irritable que d'habitude ?",
    },
  },
  {
    id: "pd-023",
    english: "Has your child been pulling at their ears?",
    category: "Pediatric",
    critical: false,
    translations: {
      es: "¿Su hijo/a se ha estado jalando las orejas?",
      zh: "你的孩子一直在拉耳朵吗？",
      ar: "هل يشد طفلك أذنيه؟",
      fr: "Votre enfant se tire-t-il les oreilles ?",
    },
  },
  {
    id: "pd-024",
    english: "Does your child attend daycare or school?",
    category: "Pediatric",
    critical: false,
    translations: {
      es: "¿Su hijo/a asiste a guardería o escuela?",
      zh: "你的孩子上托儿所或学校吗？",
      ar: "هل يذهب طفلك إلى الحضانة أو المدرسة؟",
      fr: "Votre enfant va-t-il à la crèche ou à l'école ?",
    },
  },
  {
    id: "pd-025",
    english: "Your child is going to be fine.",
    category: "Pediatric",
    critical: false,
    translations: {
      es: "Su hijo/a va a estar bien.",
      zh: "你的孩子会没事的。",
      ar: "سيكون طفلك بخير.",
      fr: "Votre enfant va bien se rétablir.",
    },
  },

  // ============================================================
  // CHRONIC CARE (25+ phrases)
  // ============================================================
  {
    id: "cc-001",
    english: "You need to monitor your blood sugar daily.",
    category: "Chronic Care",
    critical: true,
    translations: {
      es: "Necesita monitorear su azúcar en sangre diariamente.",
      zh: "你需要每天监测你的血糖。",
      ar: "تحتاج إلى مراقبة نسبة السكر في دمك يومياً.",
      fr: "Vous devez surveiller votre glycémie quotidiennement.",
    },
  },
  {
    id: "cc-002",
    english: "Have you been checking your blood pressure at home?",
    category: "Chronic Care",
    critical: false,
    translations: {
      es: "¿Ha estado revisando su presión arterial en casa?",
      zh: "你在家量血压了吗？",
      ar: "هل تقيس ضغط دمك في المنزل؟",
      fr: "Vérifiez-vous votre tension artérielle à domicile ?",
    },
  },
  {
    id: "cc-003",
    english: "It is important to take your medication every day.",
    category: "Chronic Care",
    critical: true,
    translations: {
      es: "Es importante tomar su medicamento todos los días.",
      zh: "每天按时服药很重要。",
      ar: "من المهم تناول دوائك كل يوم.",
      fr: "Il est important de prendre votre médicament chaque jour.",
    },
  },
  {
    id: "cc-004",
    english: "You need to follow a low-sodium diet.",
    category: "Chronic Care",
    critical: false,
    translations: {
      es: "Necesita seguir una dieta baja en sodio.",
      zh: "你需要遵循低钠饮食。",
      ar: "تحتاج إلى اتباع نظام غذائي منخفض الصوديوم.",
      fr: "Vous devez suivre un régime pauvre en sel.",
    },
    culturalNote: "Dietary advice must account for cultural food practices. Work with the patient on realistic alternatives.",
  },
  {
    id: "cc-005",
    english: "Regular exercise can help manage your condition.",
    category: "Chronic Care",
    critical: false,
    translations: {
      es: "El ejercicio regular puede ayudar a controlar su condición.",
      zh: "定期运动可以帮助控制你的病情。",
      ar: "التمارين المنتظمة يمكن أن تساعد في إدارة حالتك.",
      fr: "L'exercice régulier peut aider à gérer votre état.",
    },
  },
  {
    id: "cc-006",
    english: "You need to schedule a follow-up appointment.",
    category: "Chronic Care",
    critical: false,
    translations: {
      es: "Necesita programar una cita de seguimiento.",
      zh: "你需要安排一次复诊。",
      ar: "تحتاج إلى تحديد موعد متابعة.",
      fr: "Vous devez prendre un rendez-vous de suivi.",
    },
  },
  {
    id: "cc-007",
    english: "Your A1C level is too high.",
    category: "Chronic Care",
    critical: true,
    translations: {
      es: "Su nivel de A1C está demasiado alto.",
      zh: "你的糖化血红蛋白水平太高了。",
      ar: "مستوى A1C لديك مرتفع جداً.",
      fr: "Votre taux d'HbA1c est trop élevé.",
    },
  },
  {
    id: "cc-008",
    english: "Are you experiencing any side effects from your medication?",
    category: "Chronic Care",
    critical: false,
    translations: {
      es: "¿Está experimentando algún efecto secundario de su medicamento?",
      zh: "你有没有因为药物出现副作用？",
      ar: "هل تعاني من أي آثار جانبية من دوائك؟",
      fr: "Ressentez-vous des effets secondaires de votre médicament ?",
    },
  },
  {
    id: "cc-009",
    english: "You should quit smoking.",
    category: "Chronic Care",
    critical: true,
    translations: {
      es: "Debería dejar de fumar.",
      zh: "你应该戒烟。",
      ar: "يجب أن تقلع عن التدخين.",
      fr: "Vous devriez arrêter de fumer.",
    },
  },
  {
    id: "cc-010",
    english: "Let us review your current medications.",
    category: "Chronic Care",
    critical: false,
    translations: {
      es: "Revisemos sus medicamentos actuales.",
      zh: "让我们回顾一下你目前的用药。",
      ar: "دعنا نراجع أدويتك الحالية.",
      fr: "Passons en revue vos médicaments actuels.",
    },
  },
  {
    id: "cc-011",
    english: "Your kidney function needs to be monitored.",
    category: "Chronic Care",
    critical: true,
    translations: {
      es: "Su función renal necesita ser monitoreada.",
      zh: "你的肾功能需要监测。",
      ar: "يجب مراقبة وظائف الكلى لديك.",
      fr: "Votre fonction rénale doit être surveillée.",
    },
  },
  {
    id: "cc-012",
    english: "Are you managing your stress?",
    category: "Chronic Care",
    critical: false,
    translations: {
      es: "¿Está manejando su estrés?",
      zh: "你在管理你的压力吗？",
      ar: "هل تتحكم في مستوى توترك؟",
      fr: "Gérez-vous votre stress ?",
    },
  },
  {
    id: "cc-013",
    english: "You need to check your feet daily for sores.",
    category: "Chronic Care",
    critical: true,
    translations: {
      es: "Necesita revisar sus pies diariamente en busca de llagas.",
      zh: "你需要每天检查你的脚是否有溃疡。",
      ar: "تحتاج إلى فحص قدميك يومياً بحثاً عن تقرحات.",
      fr: "Vous devez examiner vos pieds quotidiennement pour détecter les plaies.",
    },
  },
  {
    id: "cc-014",
    english: "Limit your alcohol intake.",
    category: "Chronic Care",
    critical: false,
    translations: {
      es: "Limite su consumo de alcohol.",
      zh: "限制你的饮酒量。",
      ar: "قلل من تناول الكحول.",
      fr: "Limitez votre consommation d'alcool.",
    },
  },
  {
    id: "cc-015",
    english: "We may need to adjust your insulin dose.",
    category: "Chronic Care",
    critical: true,
    translations: {
      es: "Es posible que necesitemos ajustar su dosis de insulina.",
      zh: "我们可能需要调整你的胰岛素剂量。",
      ar: "قد نحتاج إلى تعديل جرعة الأنسولين الخاصة بك.",
      fr: "Nous devrons peut-être ajuster votre dose d'insuline.",
    },
  },
  {
    id: "cc-016",
    english: "Keep a journal of your symptoms.",
    category: "Chronic Care",
    critical: false,
    translations: {
      es: "Lleve un diario de sus síntomas.",
      zh: "记录你的症状日记。",
      ar: "احتفظ بسجل لأعراضك.",
      fr: "Tenez un journal de vos symptômes.",
    },
  },
  {
    id: "cc-017",
    english: "Your cholesterol levels are elevated.",
    category: "Chronic Care",
    critical: false,
    translations: {
      es: "Sus niveles de colesterol están elevados.",
      zh: "你的胆固醇水平偏高。",
      ar: "مستويات الكوليسترول لديك مرتفعة.",
      fr: "Votre taux de cholestérol est élevé.",
    },
  },
  {
    id: "cc-018",
    english: "How often do you exercise?",
    category: "Chronic Care",
    critical: false,
    translations: {
      es: "¿Con qué frecuencia hace ejercicio?",
      zh: "你多久运动一次？",
      ar: "كم مرة تمارس الرياضة؟",
      fr: "À quelle fréquence faites-vous de l'exercice ?",
    },
  },
  {
    id: "cc-019",
    english: "You need an annual eye exam.",
    category: "Chronic Care",
    critical: false,
    translations: {
      es: "Necesita un examen de la vista anual.",
      zh: "你需要每年做一次眼科检查。",
      ar: "تحتاج إلى فحص عيون سنوي.",
      fr: "Vous avez besoin d'un examen oculaire annuel.",
    },
  },
  {
    id: "cc-020",
    english: "Managing your condition is a team effort.",
    category: "Chronic Care",
    critical: false,
    translations: {
      es: "Manejar su condición es un esfuerzo en equipo.",
      zh: "管理你的病情需要团队合作。",
      ar: "إدارة حالتك هي جهد جماعي.",
      fr: "La gestion de votre état est un travail d'équipe.",
    },
  },
  {
    id: "cc-021",
    english: "Drink at least 8 glasses of water a day.",
    category: "Chronic Care",
    critical: false,
    translations: {
      es: "Beba al menos 8 vasos de agua al día.",
      zh: "每天至少喝8杯水。",
      ar: "اشرب 8 أكواب ماء على الأقل يومياً.",
      fr: "Buvez au moins 8 verres d'eau par jour.",
    },
  },
  {
    id: "cc-022",
    english: "Do you have a glucose meter at home?",
    category: "Chronic Care",
    critical: false,
    translations: {
      es: "¿Tiene un medidor de glucosa en casa?",
      zh: "你家里有血糖仪吗？",
      ar: "هل لديك جهاز قياس السكر في المنزل؟",
      fr: "Avez-vous un glucomètre à domicile ?",
    },
  },
  {
    id: "cc-023",
    english: "Report any sudden changes in your symptoms immediately.",
    category: "Chronic Care",
    critical: true,
    translations: {
      es: "Informe cualquier cambio repentino en sus síntomas inmediatamente.",
      zh: "如果你的症状有任何突然变化，请立即报告。",
      ar: "أبلغ عن أي تغيرات مفاجئة في أعراضك فوراً.",
      fr: "Signalez immédiatement tout changement soudain de vos symptômes.",
    },
  },
  {
    id: "cc-024",
    english: "We can connect you with a nutritionist.",
    category: "Chronic Care",
    critical: false,
    translations: {
      es: "Podemos conectarle con un nutricionista.",
      zh: "我们可以为你联系一位营养师。",
      ar: "يمكننا توصيلك بأخصائي تغذية.",
      fr: "Nous pouvons vous mettre en contact avec un nutritionniste.",
    },
  },
  {
    id: "cc-025",
    english: "Small changes in your lifestyle can make a big difference.",
    category: "Chronic Care",
    critical: false,
    translations: {
      es: "Pequeños cambios en su estilo de vida pueden hacer una gran diferencia.",
      zh: "生活方式的小改变可以带来大不同。",
      ar: "التغييرات الصغيرة في نمط حياتك يمكن أن تحدث فرقاً كبيراً.",
      fr: "De petits changements dans votre mode de vie peuvent faire une grande différence.",
    },
  },
];

/**
 * Get phrases by category.
 */
export function getPhrasesByCategory(category: MedicalCategory): MedicalPhrase[] {
  return medicalPhrases.filter((p) => p.category === category);
}

/**
 * Get critical phrases only.
 */
export function getCriticalPhrases(): MedicalPhrase[] {
  return medicalPhrases.filter((p) => p.critical);
}

/**
 * Search phrases by English text.
 */
export function searchPhrases(query: string): MedicalPhrase[] {
  const q = query.toLowerCase();
  return medicalPhrases.filter((p) => p.english.toLowerCase().includes(q));
}
