'use client';

import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Mountain, MapPin, Clock, ChevronDown, Paintbrush } from 'lucide-react';
import SpectrumGradient from '@/components/SpectrumGradient';
import { caveSites, type CaveSite } from '@/lib/cave-sites';

const universalSymbols = [
  {
    symbol: 'Spirals',
    description: 'Found on every inhabited continent. May represent water, cosmic cycles, the journey of the soul, or trance-state visual phenomena (entoptic patterns). The most universal motif in prehistoric art.',
  },
  {
    symbol: 'Handprints',
    description: 'Negative handprints (blown pigment around a hand) and positive handprints appear in caves across Europe, South America, Southeast Asia, and Australia. The most personal mark a human can leave: "I was here."',
  },
  {
    symbol: 'Dots & Lines',
    description: 'Rows of dots, parallel lines, and grid patterns appear in caves worldwide. Recent research suggests some may represent a proto-numerical or calendrical notation system — the earliest form of record-keeping.',
  },
  {
    symbol: 'Zigzags',
    description: 'Zigzag patterns appear in rock art from every era. They may represent water, lightning, snakes, or — according to neuropsychological research — patterns generated by the human visual cortex during altered states of consciousness.',
  },
  {
    symbol: 'Therianthropes',
    description: 'Human-animal hybrid figures appear in cave art from France to South Africa. They are widely interpreted as representing shamanic transformation — the experience of becoming or merging with a power animal during trance.',
  },
  {
    symbol: 'Vulva & Fertility',
    description: 'Abstract and naturalistic depictions of female anatomy appear in Paleolithic art across Europe. Along with Venus figurines, they suggest a widespread symbolic or ritual focus on fertility, creation, and the feminine.',
  },
];

export default function CavesPage() {
  const [expandedSite, setExpandedSite] = useState<string | null>(null);

  return (
    <div className="overflow-hidden">
      {/* Hero */}
      <section className="relative py-20 sm:py-28 px-4 sm:px-6 lg:px-8">
        <SpectrumGradient intensity="subtle" />
        <div className="relative z-10 max-w-3xl mx-auto text-center">
          <p className="text-sm font-semibold uppercase tracking-wider text-lingua-amber mb-4">
            Cave Art Interpreter
          </p>
          <h1 className="font-serif text-4xl sm:text-5xl font-bold text-text-primary leading-[1.1] mb-6">
            Humanity&apos;s{' '}
            <span className="bg-gradient-connect bg-clip-text text-transparent">First Language</span>
          </h1>
          <p className="text-text-secondary text-lg leading-relaxed max-w-2xl mx-auto">
            Long before anyone invented writing, humans were painting. On cave
            walls, on rock shelters, on cliff faces across every continent, our
            ancestors left messages that we are still learning to read. These are
            the oldest known expressions of the human mind — and they are magnificent.
          </p>
        </div>
      </section>

      {/* Cave Sites */}
      <section className="py-16 sm:py-24 px-4 sm:px-6 lg:px-8">
        <div className="max-w-5xl mx-auto space-y-6">
          {caveSites.map((site) => {
            const isExpanded = expandedSite === site.name;
            return (
              <div
                key={site.name}
                className="bg-white rounded-2xl border border-lingua-border-light shadow-sm overflow-hidden"
              >
                <button
                  onClick={() => setExpandedSite(isExpanded ? null : site.name)}
                  className="w-full p-6 sm:p-8 text-left focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-lingua-blue"
                  aria-expanded={isExpanded}
                >
                  <div className="flex items-start justify-between gap-4">
                    <div className="flex-1">
                      <h3 className="font-serif text-2xl font-bold text-text-primary mb-2">
                        {site.name}
                      </h3>
                      <div className="flex flex-wrap items-center gap-3 text-sm text-text-muted mb-3">
                        <span className="inline-flex items-center gap-1">
                          <MapPin size={13} /> {site.location}, {site.country}
                        </span>
                        <span className="inline-flex items-center gap-1">
                          <Clock size={13} /> {site.age}
                        </span>
                      </div>
                      <p className="text-sm text-text-secondary leading-relaxed">
                        {site.description}
                      </p>
                    </div>
                    <ChevronDown
                      size={20}
                      className={`text-text-muted flex-shrink-0 mt-2 transition-transform ${isExpanded ? 'rotate-180' : ''}`}
                    />
                  </div>
                </button>

                <AnimatePresence>
                  {isExpanded && (
                    <motion.div
                      initial={{ height: 0, opacity: 0 }}
                      animate={{ height: 'auto', opacity: 1 }}
                      exit={{ height: 0, opacity: 0 }}
                      transition={{ duration: 0.25 }}
                      className="overflow-hidden"
                    >
                      <div className="px-6 sm:px-8 pb-8 space-y-6">
                        {/* Significance */}
                        <div className="bg-lingua-amber/5 border border-lingua-amber/20 rounded-xl p-5">
                          <p className="text-[11px] font-semibold uppercase tracking-wider text-lingua-amber/60 mb-2">
                            Significance
                          </p>
                          <p className="text-sm text-text-secondary leading-relaxed">
                            {site.significance}
                          </p>
                        </div>

                        {/* Panels */}
                        <div>
                          <h4 className="font-serif text-lg font-bold text-text-primary mb-4 flex items-center gap-2">
                            <Paintbrush size={18} className="text-lingua-amber" />
                            Notable Panels
                          </h4>
                          <div className="space-y-4">
                            {site.notablePanels.map((panel) => (
                              <div
                                key={panel.name}
                                className="bg-gray-50 rounded-xl p-5"
                              >
                                <h5 className="font-serif text-base font-semibold text-text-primary mb-2">
                                  {panel.name}
                                </h5>
                                <p className="text-sm text-text-secondary leading-relaxed mb-3">
                                  {panel.description}
                                </p>
                                <div className="bg-white rounded-lg p-4 border border-lingua-border-light">
                                  <p className="text-[10px] font-semibold uppercase tracking-wider text-lingua-violet/60 mb-1">
                                    Interpretation
                                  </p>
                                  <p className="text-sm text-text-secondary leading-relaxed">
                                    {panel.interpretation}
                                  </p>
                                </div>
                              </div>
                            ))}
                          </div>
                        </div>
                      </div>
                    </motion.div>
                  )}
                </AnimatePresence>
              </div>
            );
          })}
        </div>
      </section>

      {/* Universal Symbols */}
      <section className="py-16 sm:py-24 px-4 sm:px-6 lg:px-8 bg-gradient-warm">
        <div className="max-w-5xl mx-auto">
          <div className="text-center mb-12">
            <h2 className="font-serif text-3xl sm:text-4xl font-bold text-text-primary mb-3">
              Universal Symbols
            </h2>
            <p className="text-text-secondary text-lg max-w-2xl mx-auto">
              These motifs appear in rock art across every continent, separated by tens of thousands of
              miles and thousands of years. What does it mean that humans everywhere made the same marks?
            </p>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-5">
            {universalSymbols.map((sym) => (
              <div
                key={sym.symbol}
                className="bg-white rounded-xl border border-lingua-border-light p-6 shadow-sm"
              >
                <h3 className="font-serif text-lg font-bold text-text-primary mb-2">
                  {sym.symbol}
                </h3>
                <p className="text-sm text-text-secondary leading-relaxed">
                  {sym.description}
                </p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Closing Quote */}
      <section className="py-20 px-4 sm:px-6 lg:px-8" style={{ backgroundColor: '#0F172A' }}>
        <div className="max-w-3xl mx-auto text-center">
          <blockquote>
            <p className="font-serif text-xl sm:text-2xl font-bold leading-relaxed text-gray-400">
              &ldquo;The humbling thing about cave art is not how different these
              people were from us — it is how similar. They loved beauty. They
              feared death. They told stories. They wanted to be remembered. Forty
              thousand years later, we are still doing the same thing, just on
              different walls.&rdquo;
            </p>
          </blockquote>
        </div>
      </section>
    </div>
  );
}
